### ISSUE TITLE
Feature request: add a clamp function

### ISSUE THREAD

**Issue by titpetric** [MikeMcl/decimal.js#101]
Having a clamp function would be a nice utility. Clamp usually limits a given value to min/max:

```
decimalValue.clamp(min, max) // returns a decimal between (min, max)
```

The examples, simplified without wrapping the decimal type would be:

```
3.clamp(1, 10) // 3
30.clamp(1, 10) // 10
-1.clamp(1, 10) // 1
```

**Comment by MikeMcl** [comment]
Added in *v10.3.0*.
