### ISSUE TITLE
.toHexadecimal limit

### ISSUE THREAD

**Issue by TGM** [MikeMcl/decimal.js#104]
Hello,
Please increase the limit of .toHexadecimal to more then 53 bits.

**Comment by MikeMcl** [comment]
Hi,
I am not sure what you are talking about.
The number of significant digits returned by the [`toHexadecimal`](http://mikemcl.github.io/decimal.js/#toHex) method is determined by the argument passed to it, or if there is no argument passed, by the current `Decimal.precision` setting.

```javascript
x = new Decimal('12345678987654321.123456789');
x.toHexadecimal();    // '0x2bdc546291f4b1.1f9add'
Decimal.precision = 30;
x.toHexadecimal();    // '0x2bdc546291f4b1.1f9add3739635f31'
// binary exponential notation is used if the precision is passed as an argument
x.toHexadecimal(40);  // '0x1.5ee2a3148fa588fcd6e9b9cb1af98921040f36ep+53'
```
