### ISSUE TITLE
Feature: Prevent toString from converting to scientific notation

### ISSUE THREAD

**Issue by nickjuntilla** [MikeMcl/decimal.js#105]
Just like in regular javascript strings are shown with scientific notation over 20 digits. This prevents transferring these numbers to other systems like for blockchain and cyrptocurrency applications.

**Comment by MikeMcl** [comment]
Use [`toFixed()`](http://mikemcl.github.io/decimal.js/#toFixed) or, for example,  [`Decimal.set({toExpPos: 40})`](http://mikemcl.github.io/decimal.js/#toExpPos).

**Comment by nickjuntilla** [comment]
Does 0 to 9e15 inclusive mean you can't get numbers for toExpPos larger than 9e15? I'm working with numbers that have a minimum of 18 places and can look like this 1000000000000000000000001

**Comment by MikeMcl** [comment]
`toExpPos` is the value of the *exponent* of the number, not the value of the number itself.

The number `1000000000000000000000000`, for example, is `1e24` in scientific notation, i.e. it has an exponent of just `24`.

**Comment by nickjuntilla** [comment]
Ok that's great. I'm going to give it another shot. That can really help especially dealing with Ethereum in ReactNative where you can't get access to the web3 library.
