### ISSUE TITLE
Does decimal js support stripTrailingZeros method?

### ISSUE THREAD

**Issue by wangzhanxu** [MikeMcl/decimal.js#108]
I want to truncate trailing zeroes, could you give me some ideas?

**Comment by MikeMcl** [comment]
This is not an "issue".

```js
n = new Decimal("1.230000")
n.toString()    // "1.23"
```

**Comment by paulrberg** [comment]
How would one strip the trailing zeros from a string formatted with `toFixed`?

```ts
const n = new Decimal("1.230000")
n.toFixed(4)
```

I would like `n` to be `1.23`, despite the higher precision (4). Basically the precision should act as an upper bound, trailing all the zeros in the process. Is this possible?

**Comment by MikeMcl** [comment]
@paulrberg 

```js
n = new Decimal("1.230000");
n.toFixed(4).replace(/0+$/, '');    // "1.23"
```

```js
n = new Decimal("1.230000");
n.toDecimalPlaces(4).toString();    // "1.23"  
```
