### ISSUE TITLE
Proper significant figure calculation

### ISSUE THREAD

**Issue by TimothyGu** [MikeMcl/decimal.js#11]
Hi,

Right now, decimal.js [strips all trailing fractional zeros](http://mikemcl.github.io/decimal.js/#faq). The FAQ quotes a possible problem when trailing zeros are not removed:

``` js
x = new BigDecimal("1.0")
y = new BigDecimal("1.1000")
z = x.add(y)                      // 2.1000

x = new BigDecimal("1.20")
y = new BigDecimal("3.45000")
z = x.multiply(y)                 // 4.1400000
```

While the example does show ambiguity, it does not take into account proper rounding [significance arithmetic](https://en.wikipedia.org/wiki/Significance_arithmetic). For example, the way it should behave is:

``` js
x = new BigDecimal("1.0")
y = new BigDecimal("1.1000")
z = x.add(y)                      // 2.1, as the first one has 1 fractional digit while the second one has 4. Rounding to 1 fractional digits.

x = new BigDecimal("1.20")
y = new BigDecimal("3.45000")
z = x.multiply(y)                 // 4.14, as the x has 3 significant figures while the second one has 6. Rounding to 3 fractional digits.
```

This way, there would be no ambiguity at all.

If proper rounding with trailing zeros is to be implemented, I don't object disabling it by default for compatibility reasons, although I do think disabling it would cause some surprises for newcomers, especially those who saw decimal.js'

> precision is specified in terms of significant digits instead of decimal places, and all calculations are rounded to the precision (similar to Python's decimal module) rather than just those involving division.

**Comment by sambrezo** [comment]
There is something wrong with add/substract when calculating decimal places.
```
> SignificanceArithmetic.add("0.6", "0.5")
'1'
```

**Comment by MikeMcl** [comment]
@sambrezo 

I don't see anything wrong. The operands have one significant digit each, so the result has one significant digit.

See [significance arithmetic](https://en.wikipedia.org/wiki/Significance_arithmetic).

If more signifcant digits are required, you can use, for example

```js
// 2 significant digits
SignificanceArithmetic.add("0.6", "0.5", 2)
"1.1"
```

Note that if you are using this code with the latest version of decimal.js, then

```js
var D = Decimal.constructor();
```
 should be changed to 

```js
var D = Decimal.clone();
```

**Comment by sambrezo** [comment]
Sorry, I was being to hasty. You're most certainly right. I am just confused that all other sig fig calculators are giving me different results.

**Comment by MikeMcl** [comment]
@sambrezo 

No, I am wrong. The answer should be "1.1" as you implied.

> When adding or subtracting using significant figures rules, results are rounded to the position of the least significant digit in the most uncertain of the numbers being summed (or subtracted). That is, the result is rounded to the last digit that is significant in each of the numbers being summed. Here the position of the significant figures is important, but the quantity of significant figures is irrelevant.

If and when you amend the code accordingly, please post it.

**Comment by sambrezo** [comment]
I have a very narrow use case and can get away with parsing the number of decimal places of a string like this:

```
function getDP(n) {
  return (n.toString().split('.')[1] || '').length
}
```

Maybe anybody knows of a more robust regular expression or can deduce the position of the least significant digit by looking at SD and other Decimal properties. Working with DP would allow usage of `toFixed`.

Also if you have to work with multiple operands, a proper solution would need variable numbers of parameters. I am afraid I can't provide said solution.
