### ISSUE TITLE
Rounding of half numbers

### ISSUE THREAD

**Issue by ActoMatics** [MikeMcl/decimal.js#110]
Hello, this is more a question rather an issue.
I have a rounding problem, I am comparing 2 objects of 2 different calculators:

The first calculator a returns the following number:  2499906909.871851
After using the decimal library on the second calculator to be identical to the first calculator  it always returns this:  499906909.8718505

And I keep getting errors since there are not equal.
Is there a way using your library to achieve the first number?  2499906909.871851 and not 499906909.8718505? 

Here is my implemntation of Decimal: 

```
 returnFixedDecimals: (result, calcResult) => {
        let decimals = result.toString().split('.');

        if (decimals.length >= 2) {
            let decLength = decimals[1].length;

            Decimal.config({ precision: decLength > 1 ? decLength - 1 : decLength, rounding: Decimal.ROUND_UP });
            let afterRound = new Decimal(calcResult);
            return afterRound;
        }
    },
```

**Comment by MikeMcl** [comment]
I am not clear about what you are trying to do, and this sort of question would be better to ask on [stackoverflow](https://www.stackoverflow.com).

If you want to round a Decimal to a number of decimal places you can use, for example:

```javascript
let result = new Decimal('499906909.8718505');
let afterRound = x.toDecimalPlaces(6);        // '499906909.871851'
```
