### ISSUE TITLE
Very long decimals

### ISSUE THREAD

**Issue by dractw** [MikeMcl/decimal.js#111]
Probably JS issue, but maybe you could help me out
For example i got some value like `99909.0000010000001900019` with 18 decimals places (very popular form for cryptocurrencies, eg. eth)

`new Decimal(99909.0000010000001900019` will output `99909.000001` 
Also  `result.d()` will output `[99909, 10]` 
This is how i currenty lost willing accuracy. Any ideas?

You can reproduce it here:
https://jsfiddle.net/zr3vx10t/

**Comment by josdejong** [comment]
Your precision is lost because you create it first as a regular number with limited precision, you should pass your number as a string instead when creating a Decimal.

**Comment by paulrberg** [comment]
From [Overcoming Javascript numeric precision issues](https://www.avioconsulting.com/blog/overcoming-javascript-numeric-precision-issues):

> Integer numbers between -(253 -1) and 253+1 are accurately represented [in JavaScript]. Beyond this threshold, not all integer numbers can be represented. You can think that in Javascript, integer numbers are accurate up to 15 digits.
