### ISSUE TITLE
Incorrect source mapping

### ISSUE THREAD

**Issue by jugimaster** [MikeMcl/decimal.js#114]
Hi,

It seems ```decimal-light```'s minified distribution contains a source mapping like:

```sourceMappingURL=doc/decimal.js.map```

.. Which is obviously _prrrrrobably_ incorrect anywhere it's actually deployed, and causes visitors' browsers to request a file that doesn't exist, which makes your production app look like it's broken.

It would be great if there were no source mapping included in the minified sources.

**Comment by MikeMcl** [comment]
Okay, I removed it in *v10.0.2*.

**Comment by jugimaster** [comment]
Awesome, thanks! :)
