### ISSUE TITLE
new Decimal('6.66e-7') return an Object. Why not a float?

### ISSUE THREAD

**Issue by yesongling** [MikeMcl/decimal.js#115]
![6 66e-7](https://user-images.githubusercontent.com/28178382/50390740-f553f900-0775-11e9-927e-3a1f0fd0cfe3.png)

Hi buddy.

I am trying to pass a science number and expect to get a float number. But actually return an object like that. Does decimal.js not support what I want to do?

I am using requireJS and import decimal.js globally.

system: Mac osx 10.13.6
browser: Chrome 71.0.3578.98 (Official Build) (64-bit)
lib: decimal.js v10.0.2

**Comment by MikeMcl** [comment]
```js
new Decimal('6.66e-3').toNumber()
```

See [toNumber](http://mikemcl.github.io/decimal.js/#toNumber).

**Comment by yesongling** [comment]
Thanks. 

toNumber does not seem to work. But toFixed work fine. I use that instead.
