### ISSUE TITLE
Will calculations using Decimal always return the same result -- are they deterministic?

### ISSUE THREAD

**Issue by cwellsx** [MikeMcl/decimal.js#116]
Calculations using ordinary JavaScript numbers may return different results on different systems -- i.e. they are not "deterministic" -- that's according to [this answer](https://stackoverflow.com/a/53783546/49942) and the comments in [this post](https://gafferongames.com/post/floating_point_determinism/) which it references.

I think this is caused by the standard (IEEE 754) not specifying the precision (i.e. only specifying the minimum precision), and the availability of different rounding modes, and possibly denormals.

There's [a __controlfp instruction](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/control87-controlfp-control87-2?view=vs-2017) which seems relevant but I don't know how that affects JavaScript.

Anyway is this also true (i.e. "results may differ on different systems and are in that sense not deterministic") of calculations performed using the Decimal library? In particular, when running on Node.js on different systems.

**Comment by MikeMcl** [comment]
The results from this library should be the same on all platforms.

I do use some of the `Math` object's methods, e.g. `Math.pow`, which it is claimed may not give the same results on all platforms - I've yet to see an example where this is the case - but not in a way which would cause this library to produce different results.
