### ISSUE TITLE
new Decimal('') will occur  error

### ISSUE THREAD

**Issue by MiaLeung01** [MikeMcl/decimal.js#117]
If I new a empty string with Decimal,   will occur an  error
new Decimal('') will occur an  error

**Comment by MikeMcl** [comment]
And the problem is?

**Comment by tychenjiajun** [comment]
> And the problem is?

Number('') is 0

**Comment by MikeMcl** [comment]
@tychenjiajun 

And?

So is `Number([])`, `Number(null)`, and `Number(false)`, and none of them are numbers either.
