### ISSUE TITLE
How to do computations with 3 decimal places (scale 3)?

### ISSUE THREAD

**Issue by thierryciot** [MikeMcl/decimal.js#118]
I have this:     
Decimal5 = Decimal.clone({ precision: 5, rounding: 1 })
new Decimal5(5).div(3)  -> outputs 1.6666
new Decimal5(55).div(3) -> outputs 18.333
new Decimal5(5555).div(3)  -> outputs 1851.6

I read that the precision is the number of significant digits (which explains the results above) but I didn't find anything on how to do computation where one specifies the number of digits to the right of the decimal point.

I'm just starting with this library and hopefully just missed something simple :)

Thanks.

**Comment by MikeMcl** [comment]
See [toDecimalPlaces](http://mikemcl.github.io/decimal.js/#toDP).

```js
Decimal.set({precision: 20});   // default
new Decimal(5555).div(3).toDecimalPlaces(5).toString();    // "1851.66667"
```

Alternatively, you could look at [bignumber.js](https://github.com/MikeMcl/bignumber.js) if you prefer to work with decimal places rather than significant digits.

**Comment by thierryciot** [comment]
Thanks.

Does changing precision affect performance? 
I did a quick test and it does not seem like it makes a difference.

**Comment by thierryciot** [comment]
thanks.
