### ISSUE TITLE
correct rounding in pow() for integer exponents

### ISSUE THREAD

**Issue by tonyofbyteball** [MikeMcl/decimal.js#119]
From pow() doc:
> _Is the pow function guaranteed to be correctly rounded?_
> 
> The return value will _almost always_ be correctly rounded, i.e. rounded as if the result was first calculated to an infinite number of correct digits before rounding. If a result is incorrectly rounded the maximum error will be 1 ulp (unit in the last place).

Does "almost always" also apply to integer exponents?  From the source code, I see that it does exponentiation by squaring in this case, bignumber.js seems to do the same but its doc doesn't have a note about the possibility of incorrect rounding.

**Comment by MikeMcl** [comment]
If it's an integer exponent, the return value will always be correctly rounded.

**Comment by tonyofbyteball** [comment]
Perfect, thanks!

**Comment by MikeMcl** [comment]
Correction.

The return value will always be correctly rounded if the integer exponent is less than or equal to `Number.MAX_SAFE_INTEGER`, i.e. `9007199254740991`.
