### ISSUE TITLE
constructor doesn't round to precision

### ISSUE THREAD

**Issue by tonyofbyteball** [MikeMcl/decimal.js#120]
Looks like the constructor keeps the full input precision before the first operation:
```
Decimal.set({precision: 2})
Decimal('1.23').pow(2)     // 1.5
Decimal('1.23').times(1).pow(2)   // 1.4
```
Is it supposed to work like this?

**Comment by MikeMcl** [comment]
Yes, see [precision](http://mikemcl.github.io/decimal.js/#precision).

**Comment by tonyofbyteball** [comment]
Understood, it is documented.  Still, to me it would look more intuitive and consistent if .times(1) didn't change the number.
