### ISSUE TITLE
Keeping track of decimal point

### ISSUE THREAD

**Issue by ouroboroscoding** [MikeMcl/decimal.js#124]
I know this is a hell of a long shot, but I figured I would ask anyway. Would it be at all possible to keep track of whether there is any decimal point in the original construction of the object?

Currently:
`var d = new Decimal('0.0');`
`console.log(d.toString());`

Would output `'0'`, which is technically correct, and in no way a bug, but it would be so much better if it instead outputted `'0.0'`.

Calling `new Decimal('0');` should still return `'0'`, as that was the original number, but Decimals specifically created with any '.0', or even '.00' as in a price, should return in the same format, or the larger of the two.

For example:
`var d1 = new Decimal('1.00');`
`var d2 = new Decimal('1.1');`
`var d3 = d1.plus(d2);`
`console.log(d3.toString());`

Would output `'2.10'`

Now, I know, if you're working with prices you could just do `d.toFixed(2)`, but that assumes you know ahead of time that's what you want, or in my case, what the user of my library wants, which I can't know.

If you're not interested in doing this, would you be interested in allowing me to do it and having it be merged into your project?

**Comment by MikeMcl** [comment]
It was a design decision made long ago not to retain fraction-part trailing zeros.

See [Why are trailing fractional zeros removed from Decimals?](http://mikemcl.github.io/decimal.js/#faq)

It would not be a simple matter to change the library in this way. 

This is the kind of thing that can be built on top of the library - as an old example, see [significant arithmetic](https://github.com/MikeMcl/decimal.js/issues/11).

**Comment by ouroboroscoding** [comment]
Yes, I already implemented it on top of the library, but obviously that's less efficient. Oh well, I figured it was a long shot, thanks for answering.
