### ISSUE TITLE
Support for toBuffer fromBuffer

### ISSUE THREAD

**Issue by Dorpheus** [MikeMcl/decimal.js#125]
Decimal.js allows for various string type serializations, such as toJSON and toBinary. However those round/alter the value which a given decimal instance actually holds in RAM. In order to preserve the exact state of a given decimal, what is the best strategy to serialize the content of a decimal into binary? 

For example: bignum.js offers "toBuffer".

the internal values "d" "e" and "s" while readable and serializable, are not writable and there is no constructor which will create a new Decimal from those values. 

Ideally the solution would store the fewest possible bytes to preserve the exact state, would be bit for bit identical after de-serialized, and would not require knowledge or access to decimal internals. 

By bit-for-bit, i would assume that would include Nan values or even possible illegal/out of bound Numbers, assuming it is possible for a Decimal to get into that state in any way. 

Alternatively a strategy which normalized all invalid states into a default NaN-like value would also be acceptable if it offered significant space savings over a simple binary storage. (maybe if sign is NaN stop serialing... ?) 

it doesnt need to be bit-packed, so sign could be as little as one byte but not necessarily 2 bits 

Thank you

**Comment by MikeMcl** [comment]
The compactness of the format would be inversely proportional to both the speed of de/serialisation and to the size and complexity of the required code.

The following is a reasonably simple and fast way of doing it. although it uses considerably more than the "fewest possible bytes":

```js
Decimal.prototype.toArray = function () {
  var a, i, k,
    d = this.d,
    e = this.e,
    s = this.s;

  if (d) {
    k = d.length;
    if (k > 1 || e < 0 || e > 6) {
      a = [e];
      for (i = 0; i < k; i++) {
        a.push(d[i++] * 1e7 + (d[i] || 0));
      }  
      a[1] *= s;
    } else {
      a = [s * d[0]];
    }
  } else {
    a = [s * 1/0];
  }

  return a;
};

Decimal.fromArray = function (a) {
  var d, i, k, x;

  if (!a) throw Error('Decimal.fromArray: Invalid argument');
  
  if (a.length > 1) {
    x = Object.create(Decimal.prototype);
    x.constructor = Decimal;
    k = a[1];
    x.s = 1 / k < 0 ? (a[1] = -k, -1) : 1;
    k = a[0];
    if (k > Decimal.maxE || k < Decimal.minE) {
      x.e = NaN;
      x.d = null;
    } else {  
      x.e = k;
      d = [];
      for (i = 1; i < a.length - 1; i++) {
        k = a[i];
        d.push(k / 1e7 | 0);
        d.push(k % 1e7);
      }
      k = a[i];
      d.push(k / 1e7 | 0);
      k %= 1e7;
      if (k) d.push(k);
      x.d = d;
    }
  } else {
    x = new Decimal(a[0]);
  }

  return x;
};

// Example
var x = new Decimal('12345.6789');
var y = x.toArray();
var z = Decimal.fromArray(y);
console.log(x.eq(z));    // true
```

**Comment by Dorpheus** [comment]
I suppose that partially answers my question: There is no built on or easy way to do this now, and not without directly poking s,e,d into a decimal object. 

While toArray may have some utility, its not quite what I was looking for.
I dont think all the values of the array are (0 <= x <= 255), so it isnt a binary memory array.

> a.push(d[i++] * 1e7 + (d[i] || 0));

will certainly make values over 255.

I was thinking of something closer to:
Decimal.prototype.toBuffer = function () {
    if (Number.isNaN(this.s)) {
        return Buffer.from([2]);
    } else {
        // estimate size of buffer needed
        // entries in d should be integers from 0 to 1e7, which take up 3 bytes each
        // sign will consume 1 byte
        // e will consume 8 bytes, with the high bit for sign
        const dSize = this.d.length * 3 + 1 + 7;
        const ret = Buffer.alloc(dSize);
        if (this.s > 0) {
            ret[0] = 0;
        } else {
            ret[0] = 1;
        }
        // serialize exponent into 7 bytes, top bit is sign
        let expv = Math.round(this.e);
        let expb1 = this.e < 0 ? 0x80 : 0x00;
        ret[1] = expb1 | (expv / Math.pow(2, 6 * 8)) & 0xFF;
        for (let eind = 5; eind >= 0; --eind) {
            ret[7-eind] = (expv / Math.pow(2, eind * 8)) & 0xFF;
        }
        ret.fill(0, 8);
        // serialize d
        for (let dndx = 0; dndx < this.d.length; ++dndx) {
            const dval = Math.round(this.d[dndx]);
            ret[8+dndx*3] = (dval / Math.pow(2, 8 * 2)) & 0xFF;
            ret[9+dndx*3] = (dval / Math.pow(2, 8 * 1)) & 0xFF;
            ret[10+dndx*3] = (dval / Math.pow(2, 8 * 0)) & 0xFF;

        }
        return ret;
    }
};

Obviously it could be improved by using fewer than 8 bytes for the exponent when the value is small.
(perhaps the low 4 bits of sign byte could indicate the bytes of exponent needed)

**Comment by MikeMcl** [comment]
> it isnt a binary memory array.

Sure, but that's as simple as 

```js
a = n.toArray();
f = new Float64Array(a);
```

or if you want to view the bytes

```js
b = new Uint8Array(f.buffer);
```

`Buffer` is Node.js only, so I would prefer not to use it.

**Comment by MikeMcl** [comment]
There are an infinite number of ways of doing this. This library is ES3 compatible, but if a compact binary format is desired then typed arrays will be required. 

One prospective specification:

Use ES5 for typed arrays.
Name the methods `toArrayBuffer` and `fromArrayBuffer`.

 `toArrayBuffer` to return an `ArrayBuffer` instance with the following binary format:

1 bit for sign.
6 bits (64 values) for the number of bits that will be used for the signed exponent.
1 to 64 bits for signed exponent.
n x 24bits for (n=x.d.length) mantissa elements.

The above would mean serialising to a minimum of 4 bytes, so values that could be represented in just 1, 2, or 3 bytes to be serialised to, and deserialised as, signed integers. I.e. if the value of a Decimal instance can be represented by an 8 bit integer, than `toArrayBuffer` returns a single byte, and so on.

NaN and signed Infinity to be represented in 4 bytes:
NaN: 32 zeros.
Infinity: 1 bit for sign, then 6 zeros and 25 ones.

Feedback and further suggestions and implementations please.

**Comment by Dorpheus** [comment]
>  A fromBuffer implementation would be great, so I could have a proper look at your solution above.

I do like your bit packing suggestion. Also, yes arraybuffers or uint8 arrays could be used instead of node's buffer (but nodes version is so nice, i almost always choose it over the browsers ones)

This implementation still not bit packed: but works in node:

```
Decimal.prototype.toBuffer = function () {
    if (Number.isNaN(this.s)) {
        return Buffer.from([2]);
    } else {
        if (!this.d || Number.isNaN(this.e)) {
            // infinity
            return Buffer.from([this.s > 0 ? 0 : 1]);
        }
        // estimate size of buffer needed
        // entries in d should be integers from 0 to 1e7, which take up 3 bytes each
        // sign will consume 1 byte
        // e will consume 8 bytes, with the high bit for sign
        const dSize = this.d.length * 3 + 1 + 7;
        const ret = Buffer.alloc(dSize);
        if (this.s > 0) {
            ret[0] = 0;
        } else {
            ret[0] = 1;
        }
        // serialize exponent into 7 bytes, top bit is sign
        let expv = Math.round(this.e);
        let expb1 = this.e < 0 ? 0x80 : 0x00;
        ret[1] = expb1 | (expv / Math.pow(2, 6 * 8)) & 0xFF;
        for (let eind = 5; eind >= 0; --eind) {
            ret[7-eind] = (expv / Math.pow(2, eind * 8)) & 0xFF;
        }
        ret.fill(0, 8);
        // serialize d
        for (let dndx = 0; dndx < this.d.length; ++dndx) {
            const dval = Math.round(this.d[dndx]);
            ret[8+dndx*3] = (dval / Math.pow(2, 8 * 2)) & 0xFF;
            ret[9+dndx*3] = (dval / Math.pow(2, 8 * 1)) & 0xFF;
            ret[10+dndx*3] = (dval / Math.pow(2, 8 * 0)) & 0xFF;

        }
        return ret;
    }
};


Decimal.fromBuffer = function (buf) {
    if (buf.length < 1 || buf[0] === 2) {
        return new Decimal(NaN);
    }
    const signByte = buf[0];
    const ret = Decimal(0);
    if (signByte == 1) {
        ret.s = -1;
    }
    if (buf.length < 11) {
        ret.d = null;
        ret.e = NaN;
        return ret;
    }

    // deserialize exponent
    const exp_sign = buf[1] & 0x80 ? -1 : +1;
    let exp = exp_sign * (buf[1] & 0x7F) * Math.pow(2, 6 * 8);
    for (let eind = 5; eind >= 0; --eind) {
        exp += Math.pow(2, eind * 8) * buf[7-eind];
    }

    // deserialize d
    ret.d = [];
    const dlen = (buf.length - 8) / 3;
    for (let dndx = 0; dndx < dlen; ++dndx) {
        ret.d[dndx] = buf[8+dndx*3] * Math.pow(2, 8 * 2) +
            buf[9+dndx*3] * Math.pow(2, 8 * 1) +
            buf[10+dndx*3] * Math.pow(2, 8 * 0);

    }
    ret.e = exp;
    return ret;
};

```
 7.878787878787878787878787878787878787878787878e+45 => 000000000000002d001ec67838838617a67838838617a67838838617a6
 -21340987129387.1231231231 => 010000000000000d2090526cc92b12c97f233f70
 Infinity => 00
 -Infinity => 01
 NaN => 02


> b = new Uint8Array(f.buffer);

This has ambiguous byte order, which might be problematic. That said, if toArray was part of decimal.js, I think I would be able to work around that, perhaps looping over the floats and individually serializing them.

**Comment by MikeMcl** [comment]
Published [decimal.js-extensions-serialize](https://github.com/MikeMcl/decimal.js-extensions/tree/master/serialize), so closing.
