### ISSUE TITLE
Epsilon is not considering in calculation

### ISSUE THREAD

**Issue by Keat0n** [MikeMcl/decimal.js#126]
Hello,

const num = new Decimal('9999').div(new Decimal('0.37')).mul(new Decimal('0.37'));
// 9998.9999999999999999
num.eq(new Decimal('9999')); // false

**Comment by MikeMcl** [comment]
You don't have to write `new Decimal('0.37')`, it's easier to just use:

```js
const num = new Decimal(9999).div(0.37).mul(0.37);
// 9998.9999999999999999
num.eq(9999); // false
```

Using a simpler example:

```js
num = new Decimal(1).div(3).mul(3);
num.toString();    // "0.99999999999999999999"
```

The result of `new Decimal(1).div(3)` is `"0.33333333333333333333"`, not `1 / 3`.

If you want to use an epsilon value, then you would need to add it yourself. 

It's simpler to just round the result using a rounding method such as `toSignificantDigits` or `toDecimalPlaces`, and it amounts to the same thing anyway.

```js
num.toSignificantDigits(1).toString();    // "1"
num.toSignificantDigits(19).toString();   // "1"
num.toSignificantDigits(20).toString();   // "0.99999999999999999999"
num.toSignificantDigits(1).toString();    // "1"
num.toSignificantDigits(19).toString();   // "1"
num.toSignificantDigits(20).toString();   // "0.99999999999999999999"   
```

See the discussion of this issue in [big.js](https://github.com/MikeMcl/big.js/issues/118).
