### ISSUE TITLE
Some tests failing in V8 7.4 

### ISSUE THREAD

**Issue by MikeMcl** [MikeMcl/decimal.js#128]
Some of the sin, sinh, tan and tanh tests fail with Node.js 12 and Chromium 74.0.3729.108, which both use V8 7.4.

See V8 issue [9196](https://bugs.chromium.org/p/v8/issues/list).

**Comment by josdejong** [comment]
Too bad Michael. Did you already find some minimal demonstrator of the issue, just using say `Math.sin`?

**Comment by MikeMcl** [comment]
A minimal test case: 

Other browsers and previous versions of V8:
`Math.pow(5, -4)      // 0.0016`

V8 7.4:
`Math.pow(5, -4)      // 0.0015999999999999999`

That's it. That's the reason for the failing tests.
The error in the `Math.pow` call at line 3679 is multiplied.
It's an easy fix here - I could just replace it with `Decimal.pow` - but it seems strange that V8 has moved to a seemingly less accurate `Math.pow` implementation.

**Comment by josdejong** [comment]
Ah, that's a clear demo! Yeah, I thought that there was a separate algorithm to calculate the power of integers which prevented round off errors. No clue whether this issueis somehow an intentional change or some unfortunate side effect.

Do you plan implementing a temporary fix for decimal.js?

**Comment by MikeMcl** [comment]
I use 'Math.pow' within the `sin` method to calculate how many times to use an argument reduction algorithm.  I only use it for negative powers of 5 between 1 and 16, which `Math.pow` has previously always provided the exact result for.

```js
Math.pow(5, -1)     //  0.2 
Math.pow(5, -2)     //  0.04 
Math.pow(5, -3)     //  0.008 
Math.pow(5, -4)     //  0.0016             V8 7.4: 0.0015999999999999999 
Math.pow(5, -5)     //  0.00032            V8 7.4: 0.00031999999999999997 
Math.pow(5, -6)     //  0.000064 
Math.pow(5, -7)     //  0.0000128 
Math.pow(5, -8)     //  0.00000256 
Math.pow(5, -9)     //  5.12e-7 
Math.pow(5, -10)    //  1.024e-7 
Math.pow(5, -11)    //  2.048e-8 
Math.pow(5, -12)    //  4.096e-9 
Math.pow(5, -13)    //  8.192e-10 
Math.pow(5, -14)    //  1.6384e-10 
Math.pow(5, -15)    //  3.2768e-11 
Math.pow(5, -16)    //  6.5536e-12
```

Anyway, I'll implement a fix/workaround before the end of the week. 

The ECMAScript specification only states that `Math.pow` "returns an implementation-dependent approximation of the result of raising base to the power exponent", so it cannot be relied upon for an exact result, particularly when calculating negative powers.

**Comment by josdejong** [comment]
Yeah, that's true unfortunately - the exact behavior is not specified in the standard :(. Looking forward to a fix!

**Comment by MikeMcl** [comment]
In V8, this issue is being tracked at https://bugs.chromium.org/p/chromium/issues/detail?id=957901

**Comment by MikeMcl** [comment]
Apologies for the delay, but I've just published *v10.2.0* that works around this issue.

The only other change is that the `+`sign  is accepted when parsing string values, e.g. `new Decimal('+1')`.

**Comment by josdejong** [comment]
That's great news! Thanks Michael.

**Comment by ValZapod** [comment]
>it seems strange that V8 has moved to a seemingly less accurate Math.pow implementation.

It is the same one used on android. Windows code is mostly closed source, there is older https://github.com/amd/win-libm/blob/master/pow.asm

As for https://github.com/MikeMcl/decimal.js/blob/7f01abd83d5632005d5f97ddbea41e069ee69a74/decimal.mjs#L3745

How much slower is that?
