### ISSUE TITLE
Fatal bug: sine()/cosine() calls taylorSeries(Ctor,0,x,x) with x=zero (d:[0] e:0 s:1) => infinite loop

### ISSUE THREAD

**Issue by Nibikibaba** [MikeMcl/decimal.js#132]
This would happen when toLessThanHalfPi() turns x to 'zero' in P.sin/P.cos (e.g. fractional part of the remainder after subtracting pi gives a number with e<minE) before calling taylorSeries() with that x.

Reproduction steps:
pi = Decimal.set({precision:30}).acos(-1);
s = Decimal.set({minE:-25}).sin(pi);  //<-- calling cos() here would loop too.

* There are not enough guards (or positioned incorrectly) in P.sin() or P.cos().
* taylorSeries() should also check on its own to guard against infinite loops.

I am writing a simple calculator and was hoping that at least trivial cases like sin(pi) cos(pi) would return something less hairy like 5.2322..e-50 and hence the temporary changing of minE (misuse?)

**Comment by MikeMcl** [comment]
Yes, it's a bug, which only appears when an approximation of Pi is passed to `sin` or `cos`, and `minE` is low enough for the return value from `toLessThanHalfPi` to be zero. The `sine` and `cosine` functions just need to check for a zero result from `toLessThanHalfPi`.

Thanks for the report.

This bug doesn't appear in the current unpublished version of this library, which can be found [here](https://github.com/MikeMcl/decimal.js/issues/130), in my last post.  Therefore, this bug will be fixed when that version is finally published.

**Comment by MikeMcl** [comment]
Fixed in *v10.3.0*.
