### ISSUE TITLE
toPrecision - not same result as in documentation

### ISSUE THREAD

**Issue by eliottvincent** [MikeMcl/decimal.js#134]
Hello,

I'm playing with the `.toPrecision()` method. I executed the code from your doc:
```js
const Decimal = require('decimal.js');

Decimal.set({ defaults: true });

const x = 45.6;
const y = new Decimal(x);

console.log(x.toPrecision()); // '45.6'
console.log(y.toPrecision()); // '45.6'
console.log(x.toPrecision(1)); // '5e+1'
console.log(y.toPrecision(1)); // '5e+1'
console.log(y.toPrecision(2, Decimal.ROUND_UP)); // '4.6e+1'
console.log(y.toPrecision(2, Decimal.DOWN)); // '4.5e+1'
console.log(x.toPrecision(5)); // '45.600'
console.log(y.toPrecision(5)); // '45.600'
```

This is the output:
```js
45.6
45.6
5e+1
5e+1
46
46
45.600
45.600
```

`toPrecision(2, Decimal.ROUND_UP)` returns '46' instead of '4.6e+1'.
`toPrecision(2, Decimal.DOWN)` returns '46' instead of '4.6e+1'.

Any idea on what I'm doing wrong?

**Comment by eliottvincent** [comment]
#### Context

* *node version*: 12.1.0
* *decimal.js version*: 10.2.0
* *environment* (node, browser): node
* *os*: macOS 10.14.5

**Comment by MikeMcl** [comment]
You are not doing anything wrong. The results are as they should be - assuming you meant to write

> toPrecision(2, Decimal.DOWN) returns '45' instead of '4.5e+1'.

The  example in the documentation is incorrect and should read `'46'` and `'45'`.
 
Note that this is the same behaviour as with JavaScript numbers:

`(45.6).toPrecision(2)    // "46"`

I'll correct the example presently or you could submit a PR.

**Comment by MikeMcl** [comment]
You are not doing anything wrong. The results are as they should be, but two of the examples in the documentation are incorrect.

`'4.6e+1'` should be `'46'`,
`Decimal.DOWN` should be `Decimal.ROUND_DOWN`, and 
`'4.5e+1'` should be `'45'`.
 
I'll correct the examples presently or you could submit a PR.
