### ISSUE TITLE
NPM Versioning might be out of date

### ISSUE THREAD

**Issue by ddeisadzevp** [MikeMcl/decimal.js#137]
https://www.npmjs.com/package/decimal.js-light/v/2.5.0
https://www.npmjs.com/package/decimal.js/v/3.0.0

**Comment by MikeMcl** [comment]
I do not know what you mean. *decimal.js* and *decimal.js-light* are separate libraries.

And the current version of *decimal.js is [here](https://www.npmjs.com/package/decimal.js).
