### ISSUE TITLE
Bower support

### ISSUE THREAD

**Issue by dejewi** [MikeMcl/decimal.js#14]
It will be nice if there will be possibility for install decimal.js via bower

**Comment by MikeMcl** [comment]
Added bower.json in v4.0.2, and registered with bower.

**Comment by mmatczak** [comment]
Versions v5.0.x are missing the bower.json file.

**Comment by josdejong** [comment]
See latest bullet in the v5.0.0 changelog ;)

https://github.com/MikeMcl/decimal.js/blob/master/CHANGELOG.md#500

**Comment by mmatczak** [comment]
@josdejong, thank you for the hint. Do you know why the bower.json was removed?
I can still use bower to install decimal.js, but some plugins, such as wiredep, need the main property from bower.json to get the right JavaScript file.

**Comment by josdejong** [comment]
I cannot answer that for @MikeMcl, but I personally hope that the JS community soon ditches bower in favor of npm. Having to deal with multiple package managers just complicates our lives unnecessarily, and in my opinion bower has no advantages at all over npm, but suffers from some serious fundamental flaws (just google for it, enough people have written about it).

**Comment by mmatczak** [comment]
I don't wan to run into discussions if bower, npm or jspm is better/more popular. Bower is still one of the de facto standards and pretty all libraries support both npm and bower. @MikeMcl: putting the bower.json would make a few people their lives easier :)

**Comment by MikeMcl** [comment]
I don't want to restore the *bower.json*, but after looking at the [blog](http://bower.io/blog/) I'm less reluctant to do so.

At the moment in this thread there seems to be one in favour of restoring it, and two against. I'll restore it if and when there are more voices in this thread in favour, then those not.

This is always the option of opening an issue with bower, asking them (again) to fallback to the *package.json* *main* field if a *bower.json* is absent.

**Comment by zetura** [comment]
Hi, I just had some issues with the bower module. It doesn't have any `main` file declared, so it isn't recognize by other tools like `wiredep` ;)
Would be great and fast to add it.
