### ISSUE TITLE
cos() throws TypeError

### ISSUE THREAD

**Issue by AlienKevin** [MikeMcl/decimal.js#140]
# Issue
When I call `new Decima(1).cos()`, node outputs the following error message:
```
TypeError: Cannot assign to read only property 'precision' of function 'function Decimal(v) {
      var e, i, t,
        x = this;

      // Decimal called without new.
      if ...<omitted>... }'
```
# Error Location
The error happens in the line below in `P.cosine` function when I run the debugger:
```
P.cosine = P.cos = function () {
    var pr, rm,
      x = this,
      Ctor = x.constructor;

    if (!x.d) return new Ctor(NaN);

    // cos(0) = cos(-0) = 1
    if (!x.d[0]) return new Ctor(1);

    pr = Ctor.precision;
    rm = Ctor.rounding;
    >>> Ctor.precision = pr + Math.max(x.e, x.sd()) + LOG_BASE; <<<
    Ctor.rounding = 1;
```

# Temporary Solution
After I removed the `'use strict';` at the top of `decimal.js`, the error goes away.

# Related issue
It seems that the issue ["Exception-safety of methods that temporarily mutate settings"](https://github.com/MikeMcl/decimal.js/issues/97) is still not addressed and the `cosine` function is still modifying the global `Decimal` constructor which throws a TypeError under strict mode.
Also, by extension all trig functions including `sin`, `cos`, `tan`, `asin`, `acos`, `atan` throws TypeError for assigning to readonly 'precision' property.

**Comment by MikeMcl** [comment]
*test.js*

```js
const Decimal = require('decimal.js');
const c = new Decimal(1).cos();
console.log(c.toString());
```

```bash
$ node test
0.5403023058681397174
```

For me to be able to help you, you need to provide more details about the JavaScript environment and code context.  This library does not make 'precision' a read-only property of `Decimal`.

> It seems that the issue "Exception-safety of methods that temporarily mutate settings" is still not addressed and the cosine function is still modifying the global Decimal constructor which throws a TypeError under strict mode.

No, it doesn't normally throw an error. 

If you want to try an amended version of the library that does not temporarily mutate settings, but is not as well tested, try

[decimal.zip](https://github.com/MikeMcl/decimal.js/files/3195354/decimal.zip)

**Comment by AlienKevin** [comment]
My project is written in TypeScript. The file that throws the type error looks like:
```ts
import Decimal from "decimal.js";
...
function sin(a: Decimal) {
    return a.sin();
}
...
export default {
    sin
    ...
}
```

And here's the debugging video:

![decimaljstypeerror](https://user-images.githubusercontent.com/22850071/67821399-35b98d00-fa93-11e9-8090-13e2abcecdc8.gif)
