### ISSUE TITLE
Need some help here

### ISSUE THREAD

**Issue by petermarks12** [MikeMcl/decimal.js#141]
I need very basic help in fixing following decimal numbers.  A small guidance will be helpful.

3.999999999999999 ->  4
3.999999999999998 ->  4
1936.0000000000002 -> 1936
364.50000000000006 -> 364.5
0.0055570000008 -> 0.005557

**Comment by acagastya** [comment]
@petermarks12 while it is unclear what exactly was that you wanted to do, the following code snippet should work for you:
`new Decimal(num).toDecimalPlace(7)`.  If you want to check the value, chain it with `valueOf`, ie: `new Decimal(num).toDecimalPlace(7).valueOf()`.
