### ISSUE TITLE
Question on Decimal.isDecimal

### ISSUE THREAD

**Issue by thierryciot** [MikeMcl/decimal.js#144]
Hi,

I'd like to understand when a Decimal is not an instance of Decimal but its obj.name is still [object Decimal].  For reference for other readers, here what the function tests:  either the instanceof or the object name property.

function isDecimalInstance(obj) {
    return obj instanceof Decimal || obj && obj.name === '[object Decimal]' || false;
  }

The reason I'm asking is that this may give me some clues on how to troubleshoot an issue that I can only reproduce in production.  

Thanks in advance (and thanks for this great library - this is the first time I've encountered any issue, which I'm pretty sure is not attributable to the library itself :) ).

Thierry.

For context below are some details on the issue I'm seeing.

The issue is that I receiving an exception: [DecimalError] Invalid argument: 1
The argument value (1) is correct - when I change the number that is being processed I get the new number output as part of the exception.  But that's only the toString representation so it's not that useful.

I have added a function that intercepts the call to the decimal addition and added the following tracing code (dec1 is the argument for which the library throws an invalid argument exception):
    console.log(`instanceof Decimal: dec1: ${dec1 instanceof Decimal} `);
    console.log(`Decimal.isDecimal: dec1: ${Decimal.isDecimal(dec1)} `);

The output is:
instanceof Decimal: dec1: false 
Decimal.isDecimal: dec1: true

**Comment by MikeMcl** [comment]
Where is `dec1` from?

**Comment by thierryciot** [comment]
It is a Decimal created earlier in the process.

**Comment by MikeMcl** [comment]
Sorry, there does not seem to be an issue here. I haven't got time to play detective.

**Comment by thierryciot** [comment]
Sorry Mike, I didn't mean for you to investigate.  I just need to understand why the isDecimalInstance function is testing either with instanceof operator or the object name property.  It seems just testing with instanceof should have been sufficient.

I'm asking because when I see my issue, the decimal is tested as true using the second condition.

thanks.

**Comment by MikeMcl** [comment]
`instanceof` can fail if an object is created in a different JavaScript context such as an iframe, for example. And I'm sure you could have found that out yourself through a simple web search.

**Comment by thierryciot** [comment]
Just wanted to close the loop for anyone else who might encounter this.  

It turned out to be a bug with a bundler.  My bundle ended up with multiple copies of decimal.js.
What was happening is that one part of the code was calling into one instance of decimal and then passing the decimal objects to another part of the code that was using another instance of decimal.js (all within the same bundle).  

So for sure no bugs in the decimal library, just wanted to leave a trace of this to help anyone else facing similar issue :)

By the way, one quick way to check if a bundle has multiple copies of the library is to open the bundle with a text editor and search for the value of PI or or LN10, ie, 3.14159265358979 as these strings are not minified and represent a good signature to search for.

Thierry.
