### ISSUE TITLE
(bug?) negated zero is negative

### ISSUE THREAD

**Issue by Mazuh** [MikeMcl/decimal.js#147]
why would `0 * (-1)` (as is `negated()` documented behavior) be considered negative?

```js
Decimal('0').negated().isNegative() // true (1)
Decimal('0').isNegative() // false (2)
```

and that is a contradition when I compare 0 with itself, negated or not:

```js
Decimal('0').negated().lessThan(Decimal('0')) // false (3)
Decimal('0').lessThan(Decimal('0')) // false (4)
Decimal('0').negated().lessThan(Decimal('0').negated()) // false (5)
```

the only weird behavior here is the first `(1)` example, the other 4 lines seem ok.

**Comment by Mazuh** [comment]
I'd be happy to fix it, but it's too weird that I'm starting to think that's intentional, tho a weird contradiction... may I have some confirmation here, @MikeMcl ?

**Comment by MikeMcl** [comment]
No fix required, thanks.

The `isNegative` method looks only at the sign of a value. not its magnitude. If it did not consider `-0` negative then it would be difficult to distinguish it from `+0` as they are considered equal.  

```js
Decimal(0).negated().valueOf();    // '-0'
```

See [signed zero](https://en.wikipedia.org/wiki/Signed_zero) from Wikipedia  or [Is Negative Zero a Number in JavaScript?](https://medium.com/coding-at-dawn/is-negative-zero-0-a-number-in-javascript-c62739f80114)

**Comment by Mazuh** [comment]
Very interesting, didn't know that. Thank you for the detailed answer and the nice article.

May you consider at least a doc update? I mean, I found your lib while trying to bypass float type limitations, so it's weird to just be ok with that without a clear documented warning or something.

**Comment by Mazuh** [comment]
considering this a no-fix, I opened a small proposal to add this warning on readme and closing this issue.

Hope you consider it!
