### ISSUE TITLE
Uncaught ReferenceError: Decimal is not defined IN Laravel

### ISSUE THREAD

**Issue by kingwkb** [MikeMcl/decimal.js#151]
npm install decimal.js --save

I try four way in app.js

require('decimal.js');
import Decimal from 'decimal.js/decimal';
import {Decimal} from 'decimal.js';
var Decimal = require('decimal.js');

I ran `npm run dev`

They are not working

**Comment by MikeMcl** [comment]
I am sorry but I am unable to help you. [Stackoverflow](https://stackoverflow.com/) is a better place to ask about your project configuration issues.
