### ISSUE TITLE
very bad issue: 1 / 9 * 9 != 1

### ISSUE THREAD

**Issue by vital0872** [MikeMcl/decimal.js#152]
I have identified, in my opinion, an unpleasant case. A very simple expression is miscalced.

```
let x = new Decimal ("1")
let y = x.div ("9").mul ("9")
y.toString () //  => 0.99999999999999999999
```

The expression "1 / 3 * 3" is also miscalced.

Config: defaults
Environment: Google Chrome

Even the native type "Number" doesn’t allow this.

**Comment by vmukhachev** [comment]
this is, probably, by design, decimal representation cannot store 1/9 exactly, use rounding or use 
rational type like provided by big-rational on npm

**Comment by MikeMcl** [comment]
I have also identified, in my opinion, an unpleasant case. A very simple word has been misspelt - it's "miscalculated", not "miscalced"!

Joking aside, I agree that it is an unpleasant case, but I am sure that you agree that 0.99999999999999999999 is *very* close to 1, and can easily become one with a little rounding as suggested above.
