### ISSUE TITLE
Feature request: Add an eval-like method for evaluating a math expression string

### ISSUE THREAD

**Issue by KBungei** [MikeMcl/decimal.js#153]
It would be convinient if there was a way to just pass a math expression as a string that contains numbers and the normal JavaScript operators and have it evaluated to a result

something like:

```JavaScript
let result = new Decimal("3+2*(7-4)/6");
```
my not-so-perfect way around that has been to use regular expressions like this 

```JavaScript
function prepExprToDeci(exprStr) {
  return "Decimal(" + exprStr.replace('+', ").add(").replace('-', ").minus(").replace('/', ").dividedBy(").replace('**', ").toPower(").replace('*', ").times(") + ")";
}
```
and I have to break down inner brackets for it to work:

```JavaScript
function evalInnerBrs(expr) {
  const innerBrRegExp = /\([\d-\+/*]+\)/;
  expr = expr.replace(/\+\-/g, '-');

  while (innerBrRegExp.test(expr)) {
    let innerBrMatches = expr.match(innerBrRegExp);

    for (let match of innerBrMatches) {
      let exprInMatch = match.replace(/\(/, '').replace(/\)/, '');
      expr = expr.replace(/^\-/g, '0-');
      let evalExprResult = eval(prepExprToDeci(exprInMatch));
      expr = expr.replace(match, evalExprResult);
    }
  }
  expr = expr.replace(/\+\-/g, '-');
  return eval(prepExprToDeci(expr));
}
```

but sometimes it fails

a model case being "5+7*(-6*5)"

perhaps you can help me improve my work around?

**Comment by MikeMcl** [comment]
I am not able to help you improve your workaround, but I did make a `Decimal.eval` method a long time ago but never published it due to the existence of [math.js](https://github.com/josdejong/mathjs), which uses this library under the hood.

I may publish it soon as a [decimal.js extension ](https://github.com/MikeMcl/decimal.js-extensions).

**Comment by MikeMcl** [comment]
[Published](https://github.com/MikeMcl/decimal.js-extensions/tree/master/evaluate).
