### ISSUE TITLE
Unable to get the raw number without going exponential when converting to string.

### ISSUE THREAD

**Issue by TheGoldenCactus11** [MikeMcl/decimal.js#155]
Hey!

I have been using insanely large numbers, and I need to get a non-exponential value where I can just see all the digits as a string. I'm not sure if I'm missing something, or it's just not able to. Please let me know!

Thanks.

**Comment by MikeMcl** [comment]
`x.toFixed()`

**Comment by TheGoldenCactus11** [comment]
Wow! Thanks, I have been looking for the past 2 days. Never would have thought to do that.
