### ISSUE TITLE
feature request:  localize numbers

### ISSUE THREAD

**Issue by c-x** [MikeMcl/decimal.js#163]
Hello,

Would it be possible to add a `toLocaleString()` function or something similar ?

I have numbers such as `11783.20` which are rendered nicely with trailing zeros with `toFixed(2)` for example but the left part isn't localized. I would like to render them with spaces, or commas, such as `11,783.20` or `11 783.20` (without loosing the precision). In short, making them human readable :)

I tried various things with the javascript toLocaleString() but it removes the trailing zeros (ex: `11783.20` becomes `11 783.2`).

Thanks!

**Comment by danmarshall** [comment]
Sorry to plug a different library, but [d3-format](https://github.com/d3/d3-format) handles this nicely.

**Comment by magicjeremy** [comment]
any way we can reopen this? would love to have this solved in the library or maybe have docs on how to use another library to format with decimal.js
