### ISSUE TITLE
Question about multiplication with large numbers that produces more zeroes

### ISSUE THREAD

**Issue by amd-9** [MikeMcl/decimal.js#164]
Greetings!

I'm stuggling to figure out how multiplication works. Seems there can be a possible bug but I'm not sure.

For example
`const result = Decimal.mul('11111111111111111111111111', 10).toFixed() `
result will be `111111111111111111110000000`
and for 
`console.log(Decimal.mul('1111111111111111111', 10).toFixed())`
result will be `11111111111111111110`

Why in first example I'm getting additional zeroes in the end?

**Comment by josdejong** [comment]
I guess you have to configure a `precision` larger than the default of 20 digits

**Comment by amd-9** [comment]
Thanks! It solved the issue

**Comment by josdejong** [comment]
👍
