### ISSUE TITLE
Trailing Zeros in toSignificantDigits method are getting ignored even if they are significant

### ISSUE THREAD

**Issue by jithureddy** [MikeMcl/decimal.js#170]
As per Significant digits concept trailing zeros after non-zero number are considered significant
![image](https://user-images.githubusercontent.com/5911189/108855154-9356de80-75e0-11eb-9705-f4323ca777f8.png)

Decimal.set({ precision: 4, rounding: 4})
const x = new Decimal(Number)

**Example 1**
Number - 0.003617357308347

Significant Digit Count - x.sd(true) - 13
Display - x.toSignificantDigits(2).toString() - 0.0036

**Example 2**
Number - 0.0090433932708675

Significant Digit Count - x.sd(true) - 14 - Here all zeros are counted
Display - x.toSignificantDigits(2).toString() - 0.009 

**Expected Result for Example 2 is - 0.009**

How to keep zero after 9 in the **`Example 2`** when we use _`toSignificantDigits`_ method ?

**Comment by MikeMcl** [comment]
Decimals do not contain trailing fraction-digit zeros, and `toSignificantsDigits` returns a Decimal, so the answer to your question is: It can't be done.  

Why not just use:

```js
x.toPrecision(2);
```

**Comment by jithureddy** [comment]
@MikeMcl Thank you for the quick response & kudos to you. It works for me. I will test various scenarios.

**Comment by jithureddy** [comment]
@MikeMcl I have number bigger than significant figures, so the toPrecision method is adding exponential notation
![image](https://user-images.githubusercontent.com/5911189/109481767-12cb2e80-7a75-11eb-8953-dc35e70b6b65.png)

How to switch between toPrecision or toSignificantDigits methods based on the number as my numbers can have decimals and whole numbers

**Comment by MikeMcl** [comment]
One of the many ways you could achieve your goal:

```js
Decimal.prototype.toPrecision = function (precision) {
   const x = this.toSignificantDigits(precision);
   let result = x.toFixed();
   let count = precision - x.precision(true);
   while (count--) result += '0';
   return result;
};

const x = new Decimal('0.000900043');
console.log(x.toPrecision(2));         // '0.00090'
```

**Comment by MikeMcl** [comment]
One of the many ways you could achieve your goal:

```js
Decimal.prototype.toPrecision = function (precision) {
   const x = this.toSignificantDigits(precision);
   let result = x.toFixed();
   let count = precision - x.precision();
   while (count--) result += '0';
   return result;
};

const x = new Decimal('0.000900043');
console.log(x.toPrecision(2));         // '0.00090'

const y = new Decimal('105.710601');
console.log(y.toPrecision(2));         // '110'
```

**Comment by jithureddy** [comment]
Thanks.. I was using the below

```
function format(number){
  const x = new Decimal(number);
  const numWord = String(number);
  const numBeforeDec = Number.isInteger(number)
      ? numWord
      : numWord.split('.')[0];
    if (numBeforeDec && numBeforeDec.length > 2) {
      return x.toSignificantDigits(2).toString();
    }
   return x.toPrecision(2);
```
