### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by jackinelon** [MikeMcl/decimal.js#171]
when i use
new Decimal(968257448813891645458).div(Math.pow(10,18)).toFixed()
the result is 968.25744881389164546
it's a big bug

**Comment by josdejong** [comment]
Have you tried configuring a precision higher than the default of `20`? You're doing a calculation with a value having 21 digits, which obviously cannot be represented with just 20 digits (the returned answer has 20 digits which makes sense). 

Also, `Math.pow(10,18)` returns a regular JavaScript `number`, which can only hold up to about 16 digits, but you're using it to represent a number having 18 digits, which can give issues too. 

> it's a big bug

Please be careful with finger-pointing. Coming across a bug in a battle-tested, widely used library _can_ happen, but more often it's a misunderstanding on the users end. A bit more humble tone, like "I don't understand why ..." would be a good idea.

**Comment by MikeMcl** [comment]
Yes, you need to increase the precision.
And use a string if a value has more than 15 significant digits. 

```js
Decimal.set({ precision: 25 });

new Decimal('968257448813891645458').div('1e18').toFixed()

// "968.257448813891645458"
```
