### ISSUE TITLE
Decimal.set is not a function

### ISSUE THREAD

**Issue by jan-osch** [MikeMcl/decimal.js#173]
Version 0.0.2
Node 14.15.5

```js
const Decimal = require('decimal');

Decimal.set({ precision: 5, rounding: 4 }); // TypeError: Decimal.set is not a function
```

**Comment by topealabi** [comment]
Hi, why was this closed? I'm getting the same issue

**Comment by MikeMcl** [comment]
@topealabi 

There was no `Decimal.set` in version 0.0.2.

I think it was introduced in version 7.0.0.
