### ISSUE TITLE
Rounding issue

### ISSUE THREAD

**Issue by rain1** [MikeMcl/decimal.js#178]
Hi!

I am looking for JS library that can do stuff precisely.

My problem is: 
`d1=new Decimal(-399.711896245283);d2= new Decimal(1000);d1.add(d2).toNumber();`

Will give me result 600.288103754717 which is wrong because when I add integer I expect decimal part to remain untouched. But with this example it changes from .7 to .2.

**Comment by BigFav** [comment]
Have you tried:
`d1=new Decimal('-399.711896245283');d2= new Decimal('1000');d1.add(d2).toNumber();`

In my experience using strings tends to work better. JS numbers are inherently imprecise.

**Comment by rain1** [comment]
Still same result.

**Comment by MikeMcl** [comment]
`-9.8 + 10 = 0.2`

**Comment by rain1** [comment]
Yea, my bad.

**Comment by munrocket** [comment]
Hello @MikeMcl I am trying to extend JS language with fma/invSqr etc. https://es.discourse.group/t/math-float-optimisation/829/4
Can you comment something on this? It’s wort it?
They recently created decimal-proposal which is probably too big dependency  for browsers and it can be a userspace libraries.

**Comment by MikeMcl** [comment]
@munrocket 

Hi there. The only feedback I have at the moment is that I don't like the opening sentence of your proposal. 

> JavaScript arithmetic is implemented in a non-standard way, compared to other languages. 

It starts the proposal off in a negative way, and it isn't at all clear what you are refering to. In fact, it was so off-putting I found it difficult to concentrate on what came after it.
