### ISSUE TITLE
base85 encoding

### ISSUE THREAD

**Issue by epicmiller** [MikeMcl/decimal.js#18]
@MikeMcl, Wondering if you'll accept a PR adding base85 encoding if I throw it up. I have an interest in saving an extra 10 bytes or so when printing out a large number. It would be nice to offer arbitrary base sizes for those of us with size constraints.

We can use the characters in the zeromq Z85 spec: http://rfc.zeromq.org/spec:32

If you want to throw in the `+` character we could actually get the encoding up to base87 (`$` is part of Z85, but `_` isn't). I figure the ordering of characters or adhering to a certain spec isn't that important as long as we retain back compat with your base64 implementation – since you're not adhering to the actual [base64 spec](https://en.wikipedia.org/wiki/Base64) at the moment.

Proposed numerals variable would look like this:
`NUMERALS = '0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ$_.-:+=^!/*?&<>()[]{}@%#+'`

**Comment by MikeMcl** [comment]
It's an interesting idea but the base conversion functionality here was not intended to be used for encoding numbers in as few characters as possible and I don't want to give it that emphasis.

There would also be a problem using the `.` character as you propose, as it is used as the decimal point, and it looks like you have included `+` twice.

One possibility is to have a `toArray` method which takes a base argument, so users could easily convert the resulting array of numbers to any characters required. Those who would like to work with large bases may also find it useful.

```
x = new Decimal('123456.789');

// Default to base 10000, i.e. the internal representation
x.toArray();      // [ 123456, 789000 ] 

// The array elements below are just example values and are not correct
x.toArray(16);    // [ 12, 9, 14, 3, 5, 1, 7 ]  
x.toArray(85);    // [ 52, 27, 84 ]  
x.toArray(1024);  // [ 945, 4 ]
```

**Comment by MikeMcl** [comment]
*v5.0.0* includes a [`toJSON`](http://mikemcl.github.io/decimal.js/#toJSON) method which returns a string representing the exact value of a Decimal in a compact base-88 based format. (I say base-88 *based* format because it is not just a simple conversion to base 88 as most decimal values cannot be represented exactly in base 88, or 85 or 87 etc.).

The Decimal can then be recreated using the [`Decimal.fromJSON`](http://mikemcl.github.io/decimal.js/#DfromJSON) method.

```js
x = new Decimal('177.7e+457');
str = x.toJSON;                 // '25jkh'
y = Decimal.fromJSON(str);
x.equals(y) ;                   // true
```
