### ISSUE TITLE
what happened to decimal.min.js  ?

### ISSUE THREAD

**Issue by divinity76** [MikeMcl/decimal.js#182]

**Comment by MikeMcl** [comment]
I got rid. 

Apologies for any inconvenience caused.

**Comment by dmitry-weirdo** [comment]
There is no `decimal.min.js ` in `10.3.1`. It was there in `10.2.1`. Could we add a minified version to the new jar versions as well?

**Comment by MikeMcl** [comment]
What new jar versions?

A minified version can be downloaded from a content delivery network such as *cdnjs*

    https://cdnjs.cloudflare.com/ajax/libs/decimal.js/10.3.1/decimal.min.js 

Alternatively, the [README](https://cdnjs.cloudflare.com/ajax/libs/decimal.js/10.3.1/decimal.min.js) gives some simple examples of how to do it yourself.

I no longer want to have the responsibility and maintenance burden of providing minified versions myself, particularly when I cannot be 100% sure the minification has been performed correctly.

**Comment by dmitry-weirdo** [comment]
The webjars, see https://mvnrepository.com/artifact/org.webjars.npm/decimal.js.

**Comment by divinity76** [comment]
>A minified version can be downloaded from a content delivery network such as cdnjs
> https://cdnjs.cloudflare.com/ajax/libs/decimal.js/10.3.1/decimal.min.js 

good enough for me, closing issue.
