### ISSUE TITLE
Decimal instance chaining breaks when used on separate statements

### ISSUE THREAD

**Issue by thanpolas** [MikeMcl/decimal.js#183]
```js
  const decInst = new Decimal(0);
  decInst.plus('0.1');
  T.assertEqual('0.1', decInst.valueOf());
```

The above test fails, with a valueOf: `'0'`, when expected should be `'0.1'`.

**Comment by thanpolas** [comment]
hmmm, that's kind of counter-intuitive: 

`add()` is documented as a static method `Decimal.add()` and `plus()` is documented as an instance method `new Decimal(val).plus(valb);` --> https://mikemcl.github.io/decimal.js/#Dadd

[Further examples make it blatantly obvious](https://mikemcl.github.io/decimal.js/#add) that the instance is mutable:

```js
0.1 + 0.2                                // 0.30000000000000004
x = new Decimal(0.1)
y = x.plus(0.2)                          // '0.3'
new Decimal(0.7).plus(x).plus(y)         // '1.1'
```

The "instance" `0.7` gets mutated twice to become a value of `1.1`. Where you do that as part of chaining or on different statements, should not have any effect, if JS language norms were to be followed. To anyone that understands how instances work, they would expect my test case to work too. 

But that is not the case.

So, I'd suggest that the authors either reconsider the instance methods and the instance's mutability or make sure it's blatantly obvious that they have hacked and altered the expected patterns and describe the new behaviours with fair notices on each instance.

**Comment by josdejong** [comment]
Thanos, the API actually _is_ consistent and immutable. Reading your last comment I see you're still misunderstanding a thing or two. I'm not sure though if you're really interested in getting to understand it: the tone at the end of your comment comes across quite arrogant to me (I hope you don't mean it like that).

**Comment by thanpolas** [comment]
I am sorry if you understood my suggestion as arrogant. 

I'd appreciate if you took the time, much like I did, to explain where I am misunderstanding a thing or two, much like I put the effort and time to do the same.

**Comment by MikeMcl** [comment]
@thanpolas 

I don't know what you're smoking, but your example doesn't show any mutation.

All the methods of this library return a new Decimal instance (or a string or number).

I don't know of any other big number libraries that don't use immutable instances. It's helpful to be able to use for example `zero = new Decimal(0)` and know that the value will not change.

`Date` objects and `moment` objects are two [examples](https://momentjs.com/guides/#/lib-concepts/mutability/) of mutable instances, but I can't think of many others, and note [that](https://maggiepint.com/2016/06/24/why-moment-js-isnt-immutable-yet/):

> Now, it is important to know that all of Moment’s maintainers agree that date and time types should be immutable. If we were sitting down and writing a new date and time library today, that is how we would make it.

**Comment by josdejong** [comment]
> I am sorry if you understood my suggestion as arrogant.

👍 typically it's a good idea to _first_ understand the library and _next_ give advice instead of the other way around 😉 

Yeah, momentjs is a good example: it's mutable API can result in nasty bugs, I've had troubles with that myself too. That's why immutable successors like luxon or date-fns are becoming more and more popular.

To go into the examples you give: 

You can indeed do either `Decimal.add(a, b)` (static function), or `a.plus(b)` (method). The result is the same, and it is just a code style preference in the end. The documentation is just correct as far as I can see.

In the example `new Decimal(0.7).plus(x).plus(y)` the initial instance `new Decimal(0.7)` does _not_ get mutated: `plus` returns a new Decimal instance without touching the original one. You can checkout whether `a` has a different value or not after calling `a.plus(...)`:

```js
const a = new Decimal(1)
const b = new Decimal(2)
const c = new Decimal(3)
const d = a.plus(b).plus(c)

a.plus(b) // this does not "do" anything effectively, since the newly created, returned Decimal is ignored

console.log(a.toString(), b.toString(), c.toString(), d.toString()) // 1, 2, 3, 6
```

Again, the docs gives a lot of examples to get to understand this. And just try out things in your developer console to verify how things work. I hope this helps.

**Comment by thanpolas** [comment]
```js
const a = new Decimal(1)
const b = new Decimal(2)
const c = new Decimal(3)
const d = a.plus(b).plus(c)
```

Thank you @josdejong, this is the example that makes sense and should be in the docs. 

@MikeMcl I am not smoking anything, you have a problem understanding feedback.

```
new Decimal(0.7).plus(x).plus(y)         // '1.1'
```

This can be read in two ways, either that the instance `new Decimal(0.7)` gets mutated and returns "1.1" or as per the example @josdejong laid out and I pasted above.

I happened to read it the first way, where the instance is mutated. That doesn't make me arrogant or smoking anything, it makes you condescending.

Enough with the adjectives though; the reality is that it is an honest mistake on my part that could have been easily avoided with better documentation.

Which is has been one of my suggestions and still stands, amend your documentation so it's not ambiguous.

I will leave this issue open and as a request to give better examples on the documentation.

**Comment by MikeMcl** [comment]
Well, I agree with the bit about it being a mistake on your part.

Look again at the docs for the [plus](https://mikemcl.github.io/decimal.js/#add) method

> Returns a new Decimal whose value is the value of this Decimal plus x, rounded to precision significant digits using rounding mode rounding.

If you found the example ambiguous, then the above should have made things clear. 

As, from the beginning of the [Methods](https://mikemcl.github.io/decimal.js/#prototype-methods) section, should:

> A Decimal instance is immutable in the sense that it is not changed by its methods.

The code examples need to be read together with the text. I prefer to keep the code examples concise by not surrounding every expression with `console.log`, and I haven't had many complaints about their clarity. 

If you want to have a go at making the documentation clearer then by all means do so, and I will certainly review any pull request you submit.

The reference to smoking was intended to be a light-hearted reference to your profile picture.
