### ISSUE TITLE
thousands separators

### ISSUE THREAD

**Issue by mjkhonline** [MikeMcl/decimal.js#190]
please add an internal thousands separators print out

**Comment by MikeMcl** [comment]
I don't understand what you mean. Please give an example.

**Comment by mjkhonline** [comment]
I mean a method which separates every 3 digits with a comma.
e.g. 12345.6789 => 12,345.6789

**Comment by MikeMcl** [comment]
See [toFormat](https://github.com/MikeMcl/toFormat).
