### ISSUE TITLE
What is the meaning of this error? Can you make it clear?  

### ISSUE THREAD

**Issue by sicaifang** [MikeMcl/decimal.js#199]
![image](https://user-images.githubusercontent.com/21259427/164171514-ff5662d4-0d18-4975-8563-2b428d59b857.png)

**Comment by sicaifang** [comment]
I didn't introduce decimal.js directly, it was "mathjs ": "8.1.0" in my project.  How do I resolve this error?

**Comment by MikeMcl** [comment]
The error shows that an attempt has been made to create a `new Decimal` from an invalid argument. The third line down in the image shows that the argument contains the sequence `fa5eb` and is therefore rejected as an invalid decimal number.

The error can be resolved by not trying to create a `new Decimal` from an invalid argument. There is no issue here as far as I can see, *decimal.js* is working as expected.

**Comment by sicaifang** [comment]
> 该错误表明已尝试`new Decimal`从无效参数创建 a。图像中的第三行显示参数包含序列`fa5eb`，因此被拒绝为无效的十进制数。
> 
> 可以通过不尝试`new Decimal`从无效参数创建 a 来解决该错误。据我所知，这里没有问题，_decimal.js_正在按预期工作。

Thank you for your reply. I think I should go to check why THE value of PI was modified after my project was packaged
