### ISSUE TITLE
Cosine mutates value...

### ISSUE THREAD

**Issue by Hypercubed** [MikeMcl/decimal.js#20]
I belive you have a bug in the cosine function here: https://github.com/MikeMcl/decimal.js/blob/master/decimal.js#L2788 that causes `.cos()` to mutate the source values.  To reproduce:

```js
var Decimal = require("decimal.js");

var x = new Decimal(-5);
console.log(x, x.isNeg());  // prints Decimal {s: -1, e: 0, d: Array[1]} true
x.cos();  // should not alter x
console.log(x, x.isNeg());  // prints Decimal {s: 1, e: 0, d: Array[1]} false
```

You can see the result here:  http://requirebin.com/?gist=f051470dccf8b530f102

**Comment by Hypercubed** [comment]
If I'm not mistaken it's toLessThanHalfPi that is missing the decimal.

**Comment by MikeMcl** [comment]
Oh thanks for finding this. Yes, `sin` is the same.

 I've make many additions and I probably should have made this a beta release for a few weeks so bugs like this could be discovered.

If you come across any other issues don't hesitate to report them. Thanks again.
