### ISSUE TITLE
What is the difference between `ROUND_HALF_UP` and `ROUND_HALF_CEIL`?

### ISSUE THREAD

**Issue by paulrberg** [MikeMcl/decimal.js#202]
The [docs](https://mikemcl.github.io/bignumber.js/#properties) define `ROUND_HALF_UP` like this:

> Rounds towards nearest neighbour. If equidistant, rounds away from zero.

And `ROUND_HALF_CEIL` like this:

> Rounds towards nearest neighbour. If equidistant, rounds towards Infinity.

I just don't see what is the difference between "away from zero" and "towards Infinity"? Using either rounding mode seems to produce the same outputs, at least for the inputs that I have used.

In what cases would the outputs diverge between these two different rounding modes?

**Comment by MikeMcl** [comment]
Rounding *away from zero* in the case of a negative number means rounding towards negative infinity rather than towards infinity.

**Comment by paulrberg** [comment]
Oh, I see. Thanks for explaining!
