### ISSUE TITLE
isPositive() should return false for zero

### ISSUE THREAD

**Issue by charmbv** [MikeMcl/decimal.js#218]
Currently the function `isPositive()` returns `true` for a zero value. This should be `false`.

**Comment by MikeMcl** [comment]
I don't really disagree but this library has [signed zeros](https://medium.com/coding-at-dawn/is-negative-zero-0-a-number-in-javascript-c62739f80114) like JavaScript numbers, and that was an early design decision I have no interest in revisiting.

```js
Decimal(-0).isNegative()    // true
Decimal(0).isPositive()     // true
```

`isZero` can be used to detect zero.
