### ISSUE TITLE
Support for mathematical expression processing without loss of precision

### ISSUE THREAD

**Issue by admincopm** [MikeMcl/decimal.js#229]
Support for mathematical expression processing without loss of precision

**Comment by josdejong** [comment]
You can do that with [mathjs](https://mathjs.org), which uses `decimal.js` under the hood when you configure it to use BigNumber:

```js
import { create, all } from 'mathjs'

const config = { 
  number: 'BigNumber', 
  precision: 64 
}
const math = create(all, config)

const result = math.evaluate('0.1 + 0.2') // BigNumber 0.3
console.log(result.toString())
```

**Comment by admincopm** [comment]
Yes, I am currently using math.js to process mathematical expressions
