### ISSUE TITLE
Floating Point Error Occuring - 

### ISSUE THREAD

**Issue by Varun-2712** [MikeMcl/decimal.js#237]
Error Occuring while following -

const divide = (a, b) => {
  return new Decimal(a).dividedBy(new Decimal(b || 1)).toNumber();
};

Case -

A - 1

B - 0.6213727366498067

A/ B on Browser Console - 1.60934

A/B Decimal - 1.6093400000000002 Floating Point

Can it be only resolved by adding precision?

**Comment by Varun-2712** [comment]
guessing this is happening when i am turning the decimal object back to a js number

**Comment by MikeMcl** [comment]
Well, you could 'resolve' it by *decreasing* precision in this case.

```
Decimal.precision = 20;
new Decimal(1).div('0.6213727366498067').toString()
// "1.6093400000000001375"

Number("1.6093400000000001375")
// 1.6093400000000002

Decimal.precision = 16;
new Decimal(1).div('0.6213727366498067').toString()
"1.60934"

Number("1.60934")
// 1.60934

**Comment by Varun-2712** [comment]
@MikeMcl even after setting the precision to 16, getting the floating point issue in 1000/2204.624420183777

**Comment by Varun-2712** [comment]
can u suggest the max precision which we can set @MikeMcl
