### ISSUE TITLE
Wrong year in the CHANGELOG for versions from 5.0.1 to 5.0.7

### ISSUE THREAD

**Issue by DaniilVeriga** [MikeMcl/decimal.js#30]
https://github.com/MikeMcl/decimal.js/blob/master/CHANGELOG.md

There is **2015** for the versions from 5.0.1 to 5.0.7, but I believe it is meant to be **2016**.

![wrongyear](https://cloud.githubusercontent.com/assets/1510884/13627202/cc0bbaf8-e5d9-11e5-91c3-82cd42aeca68.JPG)

**Comment by MikeMcl** [comment]
Fixed in *v5.0.8*.
:+1:
