### ISSUE TITLE
Decimal objects in JSON.stringify()

### ISSUE THREAD

**Issue by pkyeck** [MikeMcl/decimal.js#31]
How should I go about and handle the Decimal objects when outputting as JSON via JSON.stringify?

Right now, I get something like this:

```javascript
{
  date: "2015-12-04T00:00:00.000Z",
  value: "=13c6A"
},
{
  date: "2015-12-05T00:00:00.000Z",
  value: "=ay:T4"
}
```

**Comment by MikeMcl** [comment]
[`Decimal.fromJSON(value)`](http://mikemcl.github.io/decimal.js/#DfromJSON) can be used to get a Decimal instance back from the values.

Or, if you don't want that format to be used in response to `JSON.stringify`, you would need to overwrite `Decimal.prototype.toJSON`.

**Comment by pkyeck** [comment]
Thanks for the reply.

I was wondering why you chose the more cryptic approach of base-88 encoding instead of simply using strings. was it only size? because when we gzip the json more characters shouldn't be the problem, right?

**Comment by MikeMcl** [comment]
It was in response to #18, and yes it was just about size.

Which would result in a smaller size, gzip on a decimal string, or gzip on a base-88 string that will have about half as many characters? I don't know. Maybe the gzip on a decimal string as there are fewer symbols. 

I agree that gzipping json with decimal strings will result in better compression than using base-88 strings and not gzipping.

**Comment by josdejong** [comment]
I would opt for a decimal string representation too, though my main argument for it is that it's just so valuable when JSON is human readable/editable and easily parsable by a machine. Size would only be my second concern and indeed we have zip algorithms for that on transport and storage level.

**Comment by pkyeck** [comment]
@josdejong yes, "human readable" was why I was asking. but wanted to check the downsides before going that route.

**Comment by MikeMcl** [comment]
I think you're right @josdejong, and I think it was a mistake to include the base-88 format stuff. 

It was just something I had experimented with in response to the issue being raised, and then of thinking I might as well include rather than waste the work I had done, particularly since I was removing the base parameter from `toString`.

I am tempted to remove it, but that seems a bit unfair on anybody that may be using it.

**Comment by josdejong** [comment]
Well, you can always decide to do a breaking release where you change the toJSON behavior. For a more smooth upgrade it would be nice to still be able to deserialize data stored in the previous base-88 format, I'm not sure if that would be possible.
