### ISSUE TITLE
Way to get expanded string of long decimal

### ISSUE THREAD

**Issue by mockdeep** [MikeMcl/decimal.js#35]
I'm trying to figure out a way to get the expanded string representation of a decimal. What happens now:

```js
math.bignumber('92012382910382110000000000000000000929123091.0')
bignum.toString()
=> "9.2012382910382110000000000000000000929123091e+43"
```

What I'd like:

```js
bignum.toString() // or something like it
=> "92012382910382110000000000000000000929123091.0"
```

Is there any way to get this?

**Comment by MikeMcl** [comment]
See [toFixed](http://mikemcl.github.io/decimal.js/#toFixed).

```js
var bignum = new Decimal('92012382910382110000000000000000000929123091.0');
bignum.toString();    // '9.2012382910382110000000000000000000929123091e+43'
bignum.toFixed();     // '92012382910382110000000000000000000929123091'
bignum.toFixed(1);    // '92012382910382110000000000000000000929123091.0'
```

**Comment by mockdeep** [comment]
Is there a way to get the number of decimals from the number in order to preserve the precision?

**Comment by MikeMcl** [comment]
This isn't the appropiate place to ask general usage questions like these. Please consult the documentation or try asking a question on a website such as [stackoverflow](http://stackoverflow.com/).
