### ISSUE TITLE
Load string containing a number in base "x"

### ISSUE THREAD

**Issue by vekexasia** [MikeMcl/decimal.js#36]
Hello,

i've a string representing a number written in base 4. Is it possible to use Decimal.js's constructor to load it ?

**Comment by MikeMcl** [comment]
No, it isn't.
It is possible using an earlier version of the library: see the [version 4](https://github.com/MikeMcl/decimal.js/tree/v4.x.x) branch.
Alternatively, see [bignumber.js](https://github.com/MikeMcl/bignumber.js).
