### ISSUE TITLE
Rename Lib to be commonjs compliant

### ISSUE THREAD

**Issue by vekexasia** [MikeMcl/decimal.js#37]
Hello,

I was trying to use Decimal.js within a project which uses commonjs as module resolution.

Unfortunately the ".js" suffix makes the resolver go crazy as it thinks `require('decimal.js');` is a require for a file within the folder.

You can read more about the spec here:  http://wiki.commonjs.org/wiki/Modules/1.1

```
1. The "require" function accepts a module identifier. ...
... Module identifiers may not have file-name extensions like ".js".
```

**Comment by MikeMcl** [comment]
The library is unlikely to be renamed at this point.

What commonjs implementation are you using?
