### ISSUE TITLE
Parsing numbers as strings

### ISSUE THREAD

**Issue by anjoanjewierden** [MikeMcl/decimal.js#39]
I recently encountered the issues below in this wonderful package:

new Decimal('+12');   // Throws an error (because of the +)
new Decimal('    12 '); // Throws an error (because of the spaces)

Anjo.

**Comment by MikeMcl** [comment]
Thanks for the feedback, Anjo.

I think up to and including [version four](https://github.com/MikeMcl/decimal.js/tree/v4.x.x) of the library accepts such input as valid.

As from version five, I decided to no longer accept such values and I don't want to revisit that decision.

**Comment by anjoanjewierden** [comment]
Mike, it is of course not a major issue (in my code I only need to check for this in two places).
One consideration, JavaScript's parseFloat allows this.
