### ISSUE TITLE
Break outside of loop - fails JSLint and prevent minification working

### ISSUE THREAD

**Issue by davidhancockilfracombe** [MikeMcl/decimal.js#40]
v6.0.0
Line 2972 of decimal.js
This break seems to be outside of a loop.
This does not seem valid and fails JSLint and prevents my particular flavour of minification working.

**Comment by MikeMcl** [comment]
The break to a labelled block is perfectly valid and I don't want to refactor it.
I know Microsoft Ajax Minifier produces an error or warning, but I think the minification still works fine. 
The [issue](http://ajaxmin.codeplex.com/workitem/21992) is with the minification tool, not this library.
