### ISSUE TITLE
Compatibility with Karma

### ISSUE THREAD

**Issue by koningskristof** [MikeMcl/decimal.js#47]
When using karma for unit tests Decimal is not added to the global window object. In the tested code you can not use var x = new Decimal(1); .

It seems that this block of code is loading the library on a wrong way for Karma:
`// Node and other environments that support module.exports.
  } else if (typeof module != 'undefined' && module.exports) {
    module.exports = Decimal.default = Decimal.Decimal = Decimal;
  } `

**Comment by MikeMcl** [comment]
Anything to add?
Surely, this is an issue with Karma or your usage of it.
I'm not interested in investigating this personally.

**Comment by koningskristof** [comment]
Are you saying that decimal.js is normally working fine when testing with karma?

**Comment by MikeMcl** [comment]
I have never used Karma, perhaps raise the issue with [them](https://github.com/karma-runner/karma/issues).

**Comment by koningskristof** [comment]
Karma is a heavily ( the most? ) used JavaScript testing framework, if Decimal.js is not compatible with Karma you are using a lot of possible usage of Decimal.js.

**Comment by MikeMcl** [comment]
I recommend that you try the [karma-users group](https://groups.google.com/forum/#!forum/karma-users).

Also, you would have more chance of getting some help here if you post the details of how you are attempting to load and use this library with Karma, i.e. code, configuration files, directory structure etc..
