### ISSUE TITLE
How to import decimal in typescript project?

### ISSUE THREAD

**Issue by ipassynk** [MikeMcl/decimal.js#48]
How to import decimal in typescript project? 

I am trying to do 
```
import Decimal from 'decimal.js/decimal.es6.js';
```
and it fails with "Cannot find module 'decimal.js/decimal.es6.js'." error even the decimal.js/decimal.es6.js is in npm modules.

**Comment by MikeMcl** [comment]
I just did a quick test using

`import Decimal from './node_modules/decimal.js/decimal.es6.js';`.

and a *tsconfig.json* of

```
{
  "compilerOptions": {
    "module": "CommonJS",
    "allowJs": true,
    "outDir": "dist",
    "removeComments": true
  }
}
```

and it worked for me.

**Comment by ipassynk** [comment]
Thanks. I think this is my version of typescript. I tried with typescript 2.0.3 and it doesn't work and with 2.2.0 works but I can't move to typescript 2.2 at this moment.
