### ISSUE TITLE
Crypto dependency issue when bundling with browserify or webpack 

### ISSUE THREAD

**Issue by josdejong** [MikeMcl/decimal.js#5]
Decimal.js has a dependency on the `crypto` library. When bundling decimal.js as part of a larger application using browserify or webpack, a browser compatible version of crypto is bundled with the app by default. This works, but crypto is quite a large dependency. 

Looking at the code of decimal.js, the intention is to use native crypto functionality when in the browser, and use the crypto library when in node.js. 

I can exclude crypto when bundling my application. That works fine in node.js, but not in the browser via AMD/require.js: decimal.js thinks that we are in a node.js environment because `module` and `module.exports` are defined, and tries to load crypto via `require` rather than using the browsers native crypto implementation (see [L3598](https://github.com/MikeMcl/decimal.js/blob/master/decimal.js#L3598)). 

It would be great if this loading of crypto could be rewritten such that the browser environment is correctly detected. Maybe by just checking the ducktype way: first check whether `window` and `window.crypto` exist, and if not, fallback to loading via `require('crypto')`, and if that fails, silently disable the crypto functionality.

**Comment by ryanmcgrath** [comment]
I hope nobody minds me leaving this note here - it took me a bit of time to realize this library is what was injecting the entire `crypto` package into my build. What I'm building really doesn't require this in any way and it (like mentioned above) is a bit heavy - it looks like this library is just using crypto for random number generation, no?

The way I got around it being injected for Browserify was by just marking it as external. It might be worth documenting this somewhere?

**Comment by MikeMcl** [comment]
@ryanmcgrath 

Yes, crypto is just used for random number generation.

I think a check to see if `window` is defined needs to be added, as suggested above, to stop Browserify doing this, as the browser does not need the crypto package if it supports [crypto.getrandomvalues](http://caniuse.com/#feat=getrandomvalues).

**Comment by MikeMcl** [comment]
@ryanmcgrath

After looking through the Browserify docs, I see that the `window` check wouldn't work due to Browserify using 'static analysis' of the file.

The solution seems to be to add the following to the *package.json* here

"browser": {
    "crypto": false
  }

That should avoid the need to exclude the `crypto` package.

**Comment by soulchainer** [comment]
@MikeMcl Hi. I just want yo say that using the `"browser"` field doesn't work. At least for me. I solved the issue telling browserify to ignore `crypto`.

Thanks a bunch for leaving that note, @ryanmcgrath.

**Comment by MikeMcl** [comment]
@soulchainer 

Okay, I'll have a look at this again. I want to get it right as I am pushing a major update in a couple of weeks.
