### ISSUE TITLE
The result is "9.9999999999999999999" of 10/3*3  ?

### ISSUE THREAD

**Issue by diqye2014** [MikeMcl/decimal.js#54]
I  tried  the fllow code on https://npm.runkit.com/decimal.js

```javascript
var decimalJs = require("decimal.js")

new decimalJs
.Decimal('10')
.dividedBy('3')
.mul('3')
.toString()
```

Expect： 10
Actual: "9.9999999999999999999"

**Comment by MikeMcl** [comment]
Please look at the result of `Decimal('10').dividedBy('3')` and explain why you think that should be `10` when multiplied by `3`.
