### ISSUE TITLE
iOS 10.3 sometimes giving different outputs when given the same inputs

### ISSUE THREAD

**Issue by raing3** [MikeMcl/decimal.js#55]
I'm having troubles with this library sometimes providing different calculations on iOS 10.3 (both in Safari and Chrome). An example of a calculation which is sometimes returning different values:
```
var amount = new Decimal(10);
var taxMultiplier = new Decimal(0.06)
var taxAmount = amount.times(taxMultiplier).dividedBy(taxMultiplier.plus(1));
var taxAmountNumber = taxAmount.toNumber();
```

Sometimes taxAmountNumber will be 0.5660377358490566 (what I expect - good value) other times it is returning 0.56603760000001 (seems to be losing precision - bad value).

Notes:
 * The issue didn't occur for me on iOS 10.0 when going through reproduction steps in our application. Upon updating to iOS 10.3.2 it started occurring.
 * I have reproduced the issue on 2 different iPads running iOS 10.3.1 and iOS 10.3.2.
 * I can't get the calculations to give different outputs outside of being used in our application so can't give a simple reproduction example. :(
 * I'm currently using Decimal.js 6.0.0 but tried upgrading to 7.2.1 which hasn't resolved the issue.
 * The issue seems to occur somewhat randomly (though I can reproduce it in my application ~3 out of 4 times).
 * Restarting the browser gets us out of the bad state.
 * Putting a breakpoint and stepping into a Decimal.js function (eg. constructor or divide function and then immediately resuming execution) will get us out of the bad state and Decimal.js will return the expected values until we put it back in the bad state.
 * When we get Decimal.js into a bad state we always get the same unexpected value back for the above snippet until we return to a good state.
 * Haven't reproduced the issue in any other browser/OS.
 * We are using a non-modified Decimal.js 6.0.0 and aren't overriding any of the prototype/methods or changing precision/rounding options on the Decimal object.

Rough reproduction steps in our app:
 1. Run the above snippet in the console, we will get the good value over and over again.
 2. Interact with app to get it into a bad state.
 3. Run the above snippet in the console, we will get the bad value over and over again.

If I put a breakpoint in the divide function (immediately before the "return q;" line) I can see a number of local variables are different between when Decimal.js gives me the good value vs. when Decimal.js returns the bad value.

Good value: http://i.imgur.com/FvopYro.png
Bad value: http://i.imgur.com/kjJAirB.png

From all my testing this seems to be an obscure issue with Decimal.js specifically on iOS 10.3 (introduced at some time between iOS 10.0 and iOS 10.3.1 release).

This is currently causing big problems for us as it is resulting in the numbers we present to users being inaccurate and not matching up everywhere. I'm still trying to resolve the issue myself but lack knowledge of Decimal.js internals. If anyone has any thoughts they could share on what could be going on that would be appreciated.

**Comment by MikeMcl** [comment]
This is almost certainly related to the WebKit bug described [here](https://github.com/MikeMcl/bignumber.js/issues/120).

The bug has supposedly been fixed in WebKit, but apparently that fix has still not found its way in to the latest Safari.

Unfortunately, I don't have access to macOS or iOS so it is difficult for me to work out an optimal fix here.

If you know what you are doing, try replacing all the `shift` and `unshift` array method calls in this library with `splice` calls and let me know if that fixes the issue.

If anybody from Apple happens to read this, please send me a macOS or iOS device so it is easier for me to work around your incompetence.

**Comment by raing3** [comment]
Thanks for the suggestion Mike (as well as the additional context relating to what the potential issue here is).

I'll give it a try today and let you know how I go.

**Comment by raing3** [comment]
This seems to have fixed it. Thanks so much Mike!

I've created a PR with my changes: https://github.com/MikeMcl/decimal.js/pull/56
