### ISSUE TITLE
Add a custom decimal separator to toFormat

### ISSUE THREAD

**Issue by jsantirso** [MikeMcl/decimal.js#6]
Hello Mike,
I'm going to use your amazing decimal.js library in one of my projects, but I have had to patch the toFormat method because it's not very useful for i18n: I need to be able to choose a custom decimal separator too (instead of the dot that is forced in the library).
For example, consider some typical formats used in Spain:
    "1.234.567,8910"
    "1 234 567,8910"

You might want to add the functionality to the vanilla decimal.js library, and I would suggest adding the patched toFormat method to Big.js and BigNumber.js too because it's really useful and small.

I can't open a pull request because I wouldn't know what dependencies to edit (documentation, etc.).

Thanks!

**Comment by ankebrouwer** [comment]
any update on this? there is no 4.0.0 of toFormat (https://www.npmjs.com/package/toformat)

**Comment by MikeMcl** [comment]
@ankebrouwer 

This is the repo for *decimal.js*. Obviously, I am referring in to v4.0.0 of *decimal.js*.

What do you want, exactly?
