### ISSUE TITLE
Loses digits at Decimal construction time

### ISSUE THREAD

**Issue by qntm** [MikeMcl/decimal.js#61]
`Number.MAX_VALUE` has a precise value of 2<sup>1024</sup> - 2<sup>971</sup> =

> 179769313486231570814527423731704356798070567525844996598917476803157260780028538760589558632766878171540458953514382464234321326889464182768467546703537516986049910576551282076245490090389328944075868508455133942304583236903222948165808559332123348274797826204144723168738177180919299881250404026184124858368

This can be demonstrated (with care) by doing a little arithmetic with it:

```javascript
console.log(Number.MAX_VALUE % 10000) // 8368
```

However, when I construct a `Decimal` object from this value, it looks as if most of the decimal digits are discarded.

```javascript
Decimal.set({precision: 1000, toExpPos: 1000})
console.log(new Decimal(Number.MAX_VALUE).toString())
```

> 179769313486231570000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000

Note that the information is lost at construction time, not at stringification time:

```javascript
console.log(new Decimal(Number.MAX_VALUE).mod(10000)) // this is 0
```

The suggested fix is to convert numbers to something like `"0b" + Number.MAX_VALUE.toString(2)` at `Decimal` construction time. This retains all the digits, including fractional ones, albeit as binary. Then parse the resulting string.

**Comment by MikeMcl** [comment]
Yes, this library constructs a `Decimal` from a JavaScript number's decimal `toString` value rather than its actual binary floating point value, so, for example, `new Decimal(0.1).toString()` gives `'0.1'` rather than `'0.1000000000000000055511151231257827021181583404541015625'` .

Thanks for an interesting observation and effective workaround.
