### ISSUE TITLE
isPositive() returns true for zero

### ISSUE THREAD

**Issue by kennu** [MikeMcl/decimal.js#62]
I was surprised that isPositive() returns true when the value is zero. I assumed it would be the same as greaterThan(0). Is this behaviour by design? I think it will cause bugs because many people assume positive numbers are > 0.

**Comment by kennu** [comment]
Okay, I was thinking more in terms of mathematics since I use the library to do things I couldn't do with JavaScript numbers. I did not know about these existing semantics for isPositive. I wish there was a warning in the documentation image in README.

**Comment by MikeMcl** [comment]
I've just remembered, in the light version of this library, [decimal.js-light](https://github.com/MikeMcl/decimal.js-light), there is no signed zero, so `isPositive` and `isNegative` return`false` for zero (although I have just noticed that the exmaple in the documentation for that library contradicts this).

**Comment by sqwishy** [comment]
@MikeMcl It might be a nice to mention decimal.js-light in the documentation for decimal.js's `isPos()` and maybe this issue or an explanation concerning the behaviour, since it contradicts [some more traditional definitions of zero](http://mathworld.wolfram.com/Zero.html) and could be unexpected?
