### ISSUE TITLE
Accuracy loss

### ISSUE THREAD

**Issue by felix307253927** [MikeMcl/decimal.js#65]
console.log(Decimal.pow(2, 128).div(Decimal.pow(2, 125)).toString())
gives 7.9999999999999999999
(node.js  v8.2.1 & 6.9.1)

**Comment by MikeMcl** [comment]
Do it again, but this time print the `toString` result of each individual operation.

If after doing that you still think there is an issue, then please read the documentation.

**Comment by MikeMcl** [comment]
To help yourself understand how this library works, print the `toString` result of each individual operation. You may then realise that operations are calculated according to the current `Decimal.precision` setting.

Please read the documentation before posting issues.
