### ISSUE TITLE
TypeScript the Decimal type is decimal.Decimal instead of Decimal

### ISSUE THREAD

**Issue by DevidCIC** [MikeMcl/decimal.js#68]
When I import Decimal.js in my TypeScript project, the type is decimal.Decimal instead of decimal. This is how I imported decimal.js:
`import * as Decimal from 'decimal.js';`

and this is how I have to use it:
`private value: string | decimal.Decimal;`

Decimal.js-light does not have this problem. Importing decimal.js-light in TypeScript:
`import {Decimal} from 'decimal.js-light`

and it worked as this:
`private value: string | Decimal;`

this is how my tsconfig.json looks:
`"types": [
			"node",
			"decimal.js"
		]`

**Comment by MikeMcl** [comment]
Yes, the Declaration file needs a rewrite. I'll look at it this weekend hopefully.

**Comment by drewnoakes** [comment]
If you're maintaining the TypeScript declarations yourself then it'd be best to have them as part of the npm package directly, rather than under DefinitelyTyped. In my experience, declaration-related PRs are best handled by the project's maintainers outside of DT. Just my experience.

I'm evaluating this library in my TypeScript project. Looks amazing so far, so thanks for sharing.

**Comment by DevidCIC** [comment]
@drewnoakes decimal.js-light is working really good with TypeScript. Unfortunately I need the round function that is why I switched to decimal.js. Anyway the library is actually really good.

**Comment by drewnoakes** [comment]
@DevidCIC thanks for the feedback. It matches my experience so far. It seems like a great library and the light variant works very well with TypeScript out-of-the-box.

**Comment by MikeMcl** [comment]
I've just published some new Typescript typings.

Use
```js
import Decimal from "decimal.js"
``` 
or 
```js
import {Decimal} from "decimal.js"
```

**Comment by DevidCIC** [comment]
Great now everything works just as in decimal.js-light.

I had only to remove @types/decimal.js
`npm uninstall --save @types/decimal.js`
