### ISSUE TITLE
It would be useful to have some kind of API helper for resetting Decimal to default state

### ISSUE THREAD

**Issue by SergeyLastochkin** [MikeMcl/decimal.js#69]
Thank you for designing and implementing this library. It is reasonable and useful.

While integrating it, I found one aspect that was not addressed by API or mentioned in manual page.

Decimal is stateful library. State of Decimal object could be subtly affected in **ANY** place of site.
If I use default Decimal without any wrappers, then:

1. Any {new/existing/changed} {in-house/third-party} module must be audited to check how it affects Decimal state. That's a lot to audit!

2. Real-world sites often have a lot of client-side JS scripts loaded from different domain - for example - google tracking scripts. If Decimal has state then it becomes possible for third-party sites to affect results of you decimal calculations.

It's too much to fit one's head. From my experience things like tend to become debugging and maintenance nightmare.

I feel that Decimal API would be improved if it would provide some kind of normalization/reset mechanism out of box.

I assume this form of API could be intuitive and practical:
```
D9 = Decimal.clone();
D9.reset();     // <-- function that resets D9 to defaults found at the beginning of Decimal.js
D9.set({ precision: 9 });
```

So if one wants, he can use old flow:
```
*start program*
{zeroState}-{relative-change}-{relative-change}-{relative-change}-{relative-change}
*end of program*
```
It's reliable for small programs/utilites.

But with new API one would have alternative to have a flow like:
```
*start program*
{zeroState}-{relative-change}-{relative-change}-
{zeroState}-{relative-change}-{relative-change}-
{zeroState}-{relative-change}
*end of program*
```
It allows separation of concerns which is a backbone for reliable project of any scale.

**Comment by MikeMcl** [comment]
Yes, I agree with your reasoning.

I would prefer to always return a new constructor with the default settings if no argument is passed, but that behaviour doesn't fit semantically with a `clone` method. In my other library, *bignumber.js*, from which this library was originally derived, I have an `another` method that does just that - but it's an unusual name for a method, so here I used `clone` instead and changed the behaviour.

I will consider adding a `reset` method as you suggest. Usefully, it could also be used to reset the original Decimal constructor to default settings .

**Comment by MikeMcl** [comment]
From *v8.0.0* the configuration can be reset by setting a `defaults` property to `true`.

For example,

```js
// Create a new constructor with the same configuration as this constructor
Decimal.clone()

// Create a new constructor with the same configuration as this constructor but set precision to 50
Decimal.clone({ precision: 50 })

// Create a new constructor with the default configuration
Decimal.clone({ defaults: true })

// Create a new constructor with the default configuration but set precision to 50
Decimal.clone({ precision: 50, defaults: true })

// Reset the configuration of this constructor to default values
Decimal.set({ defaults: true })

// Reset the configuration of this constructor to default values but set precision to 50
Decimal.set({ precision: 50, defaults: true })
```

Thanks for your suggestion.

**Comment by SergeyLastochkin** [comment]
Thank you for implementing this feature.

And if I may - could you explain reason why have you decided to use
```
Decimal.set({ precision: 50, defaults: true })
Decimal.clone({ precision: 50, defaults: true })
```
over
```
Decimal.reset().set({ precision: 50 })
Decimal.clone().reset().set({ precision: 50 })
```
?
To specify: I'm not nitpicking rather I'm genuinely interested to better understand benefits of new form or reasons for it.

**Comment by MikeMcl** [comment]
The reasons are that

1) adding a `reset` method seems like API bloat - there is a higher bar to adding a new method than to adding a new property to the configuration object. I don't want to add any other configuration methods - `set` and `clone` are enough.

2) it isn't clear enough what `Decimal.reset` means. Reset to what? A previous configuration? The default configuration? Why is that configuration so special that it deserves its own method? Ultimately, in my opinion, it isn't and it doesn't.

I think `Decimal.reset` was a good suggestion, and I came close to implementing it.
