### ISSUE TITLE
Manual

### ISSUE THREAD

**Issue by SergeyLastochkin** [MikeMcl/decimal.js#70]
This line seems to be incorrect:
`z = x.multiply(y)`
https://github.com/MikeMcl/decimal.js/blob/master/doc/API.html#L2598

it should be
`z = x.mul(y)`
(reason: present version of Decimal.js API doen't have 'multiply' method, but it has 'mul')

**Comment by MikeMcl** [comment]
Thanks for your efforts, but that snippet of code is demonstrating the behaviour of a `BigDecimal` library not *decimal.js*.
