### ISSUE TITLE
Buggy `.toBinary()` …

### ISSUE THREAD

**Issue by jonathanmarvens** [MikeMcl/decimal.js#72]
Hi there.

I’m currently doing some large *integer* calculations using this library and while using the `.toBinary()` method, I noticed that the results I keep getting are __incorrect__.

__E.g.:__
```javascript
const Decimal = require('decimal.js')

Decimal.set({
  modulo: Decimal.ROUND_DOWN,
  rounding: Decimal.ROUND_DOWN
})

const maxUInt64 = (new Decimal(2))
  .toPower(64)
  .minus(1)

console.log(maxUInt64.toHex()) // Prints '0xffffffffffffffff', as expected.
console.log(maxUInt64.toBinary()) // Prints '0b1111111111111111111100000000000000000000000000000000000000000000', which is incorrect.
```

I briefly looked at the implementation code, and *as I understand it*, this is a bug. (I mean, I can’t see why this would be the expected behavior anyway …)

\- Jonathan

**Comment by jonathanmarvens** [comment]
Hey, I was attempting to fix this issue. I know the issue is in the [`convertBase` function](https://github.com/MikeMcl/decimal.js/blob/a0b78b62752b98a0b8cec2e0787c068ec896c653/decimal.js#L2608-L2628), but, to be honest, the function, as written, makes it a bit difficult to keep track of the different states as the conversion happens. I’m happy to spend some more time on it and make a PR, but I figured this might be a quick fix for you (@MikeMcl) since the code is probably immediately obvious to you.

Thanks.

\- Jonathan

**Comment by jonathanmarvens** [comment]
@MikeMcl Are you okay with it if I write a new `convertBase` function that makes the functionality at least slightly clearer (and easier to prove that it’s doing the right thing)?

**Comment by jonathanmarvens** [comment]
Wait, it looks like this behavior is due to the [*significant digits* behavior](https://github.com/MikeMcl/decimal.js/blob/a0b78b62752b98a0b8cec2e0787c068ec896c653/decimal.js#L3845-L3870)? So it is the expected behavior?

**Comment by MikeMcl** [comment]
No, it's not buggy, see [toBinary](http://mikemcl.github.io/decimal.js/#toBinary).

**Comment by jonathanmarvens** [comment]
@MikeMcl Thank you. Is this default behavior really ideal though? I now understand why it works this way, but it still feels quite strange to me.

\- Jonathan

**Comment by MikeMcl** [comment]
The behaviour is consistent with the rest of the library, integers are treated the same as non-integers and operations are performed according to the current `precision` setting, for example with the default `precision` of `20`

```js
new Decimal('12345678909876543210123456789').times(1)
//                 "12345678909876543210000000000"
```
