### ISSUE TITLE
A value-testing method on the constructor

### ISSUE THREAD

**Issue by tonisostrat** [MikeMcl/decimal.js#74]
To explain, a method mirroring ES's default `Number.isInteger()`. Currently there doesn't seem to be a concise and clear-cut way to determine whether a random object is a _Decimal_ or not.

**Comment by MikeMcl** [comment]
It would be very simple to just add a property to the prototype like I did with *bignumber.js*

```Decimal.prototype.isDecimal = true'

Or do you think it better to make it a method? 
If so, why?

**Comment by tonisostrat** [comment]
Wouldn't that potentially clash with another library that also adds the same property to its prototype? The probability might be miniscule but it does exist.

I would add it as a method to the global constructor:

```
let n = new Decimal(123);

Decimal.isDecimal(n) // true
```

**Comment by josdejong** [comment]
Just FYI: math.js also used properties defined on the prototypes to figure out what the type of an object is, like `Decimal.prototype.isDecimal`. Works great. For security reasons though we had to change it to to using methods like `Decimal.isDecimal(...)`, to prevent objects from faking what they really are.

**Comment by MikeMcl** [comment]
This is how the popular JavaScript date library, Moment.js does it:

```js
export function isMoment (obj) {
    return obj instanceof Moment || (obj != null && obj._isAMomentObject != null);
}
```

So basically, if `instanceof` fails, it's just checking for the presence of the `_isAMomentObject` property. This doesn't seem much different than what I suggested above, which I prefer over

```js
Decimal.prototype._isDecimalObject = true
```

@josdejong 

What does your method check to make it reliable?

**Comment by josdejong** [comment]
In mathjs we don't use `instanceof` because that would make it painful to share data between different instances of mathjs, but basically check whether an `isDecimal` property exists on the prototype of the constructor (explained also in the code comments):

https://github.com/josdejong/mathjs/blob/master/lib/core/typed.js#L22-L73

Math.js has to do with security because it has an expression parser allowing arbitry input from users, decimal.js may not need a similar solution but it may at least be interesting to know :).

**Comment by MikeMcl** [comment]
Thanks, Jos.

I had just deleted the question before you posted because I had decided how to implement it.

I'm going to do it in a similar way to the `isBigNumber` [method](https://github.com/josdejong/mathjs/blob/master/lib/utils/bignumber/isBigNumber.js).

**Comment by josdejong** [comment]
👍

**Comment by tonisostrat** [comment]
@MikeMcl, that sounds good.

This is what I did in the meantime:
```
Decimal.isDecimal = value => value && value.constructor === Decimal;
```

**Comment by MikeMcl** [comment]
That would not work if the value was created by a different Decimal constructor (created by`Decimal.clone()`). Apparently it would also not work if multiple copies of decimal.js are imported, see [here](https://github.com/MikeMcl/bignumber.js/issues/111).

Ultimately, there is no totally reliable way of doing it. It is just going to come down to checking for the presence or value of a property on `value` or `value.constructor`

```
function isDecimal(value) {
  return value && value.constructor.EUCLID === 9 || false;
}
```

Therefore my preference is not to implement a value-testing method or add a property to the prototype at all. 

Leave it to the user, who can use `instanceof Decimal` (which works even if the value was created by a different Decimal constructor) and, beyond that, the duck-typing of their choice.

**Comment by MikeMcl** [comment]
Added `Decimal.isDecimal` method in *v8.0.0*.
