### ISSUE TITLE
TypeScript declaration file exports

### ISSUE THREAD

**Issue by MikeMcl** [MikeMcl/decimal.js#76]
Currently the declaration file includes `export default Decimal` and `export declare class Decimal` which enables the library to be imported using, respectively,

```js
import Decimal from "decimal.js"
```
or
```js
import {Decimal} from "decimal.js"
```
This works fine, but the JavaScript generated by the TypeScript compiler (with `'commonjs'` as the module type) then uses `decimal_js_1.Decimal` or `decimal_js_1["default"]` for any reference to `Decimal`.

An alternative would be to use `export = Decimal` in the declaration file and remove the other top-level exports.

This would mean that the library would then need to be imported using either

```js
import * as Decimal from "decimal.js"
```
or
```js
// TypeScript-specific, not valid ES6 module syntax.
import Decimal = require('decimal.js')
```

The advantage would be the cleaner JavaScript generated by the TypeScript compiler.

It is possible that some loaders (AMD?) may need the `export = Decimal` version, to work correctly.

Do any TypeScript users have any thoughts about this, any knowledge of the implications for different loaders, or any preferences here?

**Comment by chrisguttandin** [comment]
I personally would prefer the non-default style.

```typescript
import { Decimal } from 'decimal.js';
```

It's a bit more explicit. However, when I try to use the current version (v7.5.1) like that, it is not transpilable with webpack & ts-loader to ES5 anymore.

But for the time being the default export works great:

```typescript
import Decimal from 'decimal.js';
```
