### ISSUE TITLE
typings for toFormat are wrong

### ISSUE THREAD

**Issue by dfederm** [MikeMcl/decimal.js#78]
In the d.ts file I see:

```
  // Requires `toFormat`.
  toFormat?(decimalPlaces: number, rounding: DecimalRounding): string;
```

But according to the docs for `toFormat`, it can be called with no args.

Also, it's kind of weird that the typings of `toFormat` are even in `decimal.js`. Shouldn't `toFormat` provide the specific typings it's extending itself? That way decimal,js` doesn't have to know about its extensions at all, let alone a specific version of its extensions.

**Comment by MikeMcl** [comment]
I agree. Fixed in *v9.0.0*.
