### ISSUE TITLE
Expose `toStringBinary`

### ISSUE THREAD

**Issue by Hypercubed** [MikeMcl/decimal.js#79]
I would like to convert a decimal to an arbitrary base.  Would you consider exposing the internal  `toStringBinary` either as a static method or on the prototype?

**Comment by MikeMcl** [comment]
I'd like to help but I don't want to expose that function.
It would require substantial changes anyway for it to be used to convert arbitrary bases.
There is a [version 4](https://github.com/MikeMcl/decimal.js/tree/v4.x.x) branch which has that ability.
A base conversion extension (like [toFormat](https://github.com/MikeMcl/toFormat)) is another possibility.
