### ISSUE TITLE
Mutliplication with -.0001 Error

### ISSUE THREAD

**Issue by ahammonds7** [MikeMcl/decimal.js#85]
`Decimal('-.0001').mul(100).toNumber()` doesn't return what you would expect...It should return `-.01`, but it returns `NaN` instead.

**Comment by MikeMcl** [comment]
Works fine for me. Try it for yourself in a console [here](http://mikemcl.github.io/decimal.js/).

**Comment by ahammonds7** [comment]
That's weird... When I ran it in the console on your link I see it working fine, but in our app it doesn't seem to work. Could it be something with the precision? This is the internal Decimal function when I do `console.log(Decimal('-.0001').mul(100))`

```
Decimal {
  internal: '0.-1',
  as_int: { value: 0, exp: -2 },
  add: [Function],
  sub: [Function],
  mul: [Function],
  div: [Function],
  toString: [Function],
  toNumber: [Function] }
```

**Comment by MikeMcl** [comment]
I don't think you are using this library.
There are no `internal` or `as_int` properties here.

**Comment by ahammonds7** [comment]
That was it! I have officially switched to yours and it works great!! Thanks!
