### ISSUE TITLE
Can 10/3*3 be "10" instead of "9.99999999"?

### ISSUE THREAD

**Issue by dickenwong** [MikeMcl/decimal.js#86]
Under this package,
```javascript
const ten = new Decimal(10);
const three = new Decimal(3);
ten.div(three).mul(three).toString(); // => '9.9999999999999999999'
```
Theoretical, /3 and *3 can cancel out each other, giving an answer of strict "10".
So technically, is it possible to achieve this?

**Comment by MikeMcl** [comment]
Yes, look for a library that stores numbers as fractions.

**Comment by ceremcem** [comment]
https://github.com/josdejong/mathjs seems to perform such operations.

**Comment by josdejong** [comment]
https://github.com/josdejong/mathjs seems to perform such operations.

@ceremcem sorry but that is not the case (mathjs uses decimal.js under the hood btw). 

Floating point numbers with a finite number of digits always have round-off errors. Only Fractions can help you out here, or you can simply round outputs displayed on screen to look nicer for the user.

http://mathjs.org/docs/datatypes/bignumbers.html#limitations 
http://mathjs.org/docs/datatypes/numbers.html#roundoff-errors

**Comment by ceremcem** [comment]
Interesting. I tried the same case (again) with both of the libraries:

```js
ls> x = math.chain 10 .divide 3
{ [Number: 3.3333333333333335] value: 3.3333333333333335 }
ls> x * 3
10
ls> console.log "result is: #{math.chain 10 .divide 3 .multiply 3}"
result is: 10

```

```js
ls> require! 'decimal.js': Decimal
ls> x = new Decimal(10)
ls> y = x .div 3 
ls> console.log "result is: #{y * 3}"
result is: 10
ls> console.log "result is: #{x .div 3 .mul 3}"
result is: 9.9999999999999999999
```

Now I'm unable to understand what is going on here.... Why is `y * 3 is 10` but `x / 3 * 3 isnt 10`?

**Comment by josdejong** [comment]
Apparently regular JavaScript numbers (with about 16 decimals) are not hitting a round-off error when calculating `(10 / 3) * 3`, but a decimal.js number with 20 decimals is.

**Comment by MikeMcl** [comment]
Using JavaScript numbers:
```js
(10 / 3).toFixed(51)    // "3.333333333333333481363069950020872056484222412109375"
```
which multiplied by 3 is
```js
10.000000000000000444089209850062616169452667236328125
```
which is shown as 10 when displayed to a precision of about 16 decimal digits, as JavaScript does.

**Comment by MikeMcl** [comment]
Using JavaScript numbers:
```js
(10 / 3).toFixed(51)        //  "3.333333333333333481363069950020872056484222412109375"

(10 / 3 * 2).toFixed(51)    //  "6.666666666666666962726139900041744112968444824218750"

   // (10 / 3 * 3) 'should' be "10.000000000000000444089209850062616169452667236328125"
(10 / 3 * 3).toFixed(51)    // "10.000000000000000000000000000000000000000000000000000"

```
Notice that the result of `(10 / 3 * 3)` is being rounded but the result of `(10 / 3 * 2)` is not.

Exactly why and how this happens may be a good question to ask on Stackoverflow.

**Comment by ceremcem** [comment]
@MikeMcl Thank you for showing the insides. What I meant above is that it was weird to get 

```ls
ls> console.log "result is: #{y * 3}"
result is: 10
ls> console.log "result is: #{x .div 3 .mul 3}"
result is: 9.9999999999999999999
```

because they are (seem to be) the same operation to me anyway. 

@josdejong I can't know better than you, of course :) Also I can't find any library that claims to handle this situation properly. 

I had been handling this problem by storing two numbers in an array and evaluate the result everytime I needed. If this is the way to go here too, I might be end up writing an extension.

**Comment by josdejong** [comment]
> As it says fraction.js can handle this, so what is the problem about that?

Floating point data types like `number` of JavaScript and `Decimal` have a limited number of digits, therefore they per definition have round-off errors. Having more digits will make the problem smaller but it doesn't go away.

Fractions do not have round-off errors. Drawback is that not all calculations can be done with fractions, for example `sin` and `sqrt`, cannot be calculated using fractions. If you only need basic arithmetics (+ - / * etc), using Fractions is a great solution.
