### ISSUE TITLE
Add BigNumber implementations of pi and e

### ISSUE THREAD

**Issue by josdejong** [MikeMcl/decimal.js#9]
It would be nice to have BigNumber implementations of `pi` and `e` in Decimal.js. The constant `e` is easy, `var e = new Decimal(1).exp()`. Pi can be calculated with a series expansion. I just tried two relatively simple/short expansions:

**The Bailey-Borwein-Plouffe formula**

``` js
  Decimal.config({precision: 100});

  function pi() {
    // the Bailey-Borwein-Plouffe formula
    // http://stackoverflow.com/questions/4484489/using-basic-arithmetics-for-calculating-pi-with-arbitary-precision
    var p16 = new Decimal(1);
    var pi = new Decimal(0);
    var precision = Decimal.config().precision;

    var one = new Decimal(1);
    var two = new Decimal(2);
    var four = new Decimal(4);
    var k8 = new Decimal(0);

    for (var k = new Decimal(0); k.lte(precision); k = k.plus(one)) {
      // pi += 1/p16 * (4/(8*k + 1) - 2/(8*k + 4) - 1/(8*k + 5) - 1/(8*k+6));
      // p16 *= 16;
      //
      // a little simpler:
      // pi += p16 * (4/(8*k + 1) - 2/(8*k + 4) - 1/(8*k + 5) - 1/(8*k+6));
      // p16 /= 16;

      var f = four.div(k8.plus(1))
          .minus(two.div(k8.plus(4)))
          .minus(one.div(k8.plus(5)))
          .minus(one.div(k8.plus(6)));

      pi = pi.plus(p16.times(f));
      p16 = p16.div(16);
      k8 = k8.plus(8);
    }

    return pi;
  }

  var calculatedPi = pi();
```

**Machin's formula**

``` js
  Decimal.config({precision: 100});

  // arctan(x) = x - x^3/3 + x^5/5 - x^7/7 + x^9/9 - ...
  //           = x - x^2*x^1/3 + x^2*x^3/5 - x^2*x^5/7 + x^2*x^7/9 - ...
  function arctan(x) {
    var y = x;
    var yPrev = NaN;
    var x2 = x.times(x);
    var num = x;
    var sign = -1;

    for (var k = 3; !y.equals(yPrev); k += 2) {
      num = num.times(x2);

      yPrev = y;
      y = (sign > 0) ? y.plus(num.div(k)) : y.minus(num.div(k));
      sign = -sign;
    }

    return y;
  }

  function pi() {
    // Machin: Pi / 4 = 4 * arctan(1 / 5) - arctan(1 / 239)
    // http://milan.milanovic.org/math/english/pi/machin.html

    // we calculate pi with a few decimal places extra to prevent round off issues
    var DecimalPlus = Decimal.constructor({precision: Decimal.config().precision + 4});
    var pi4th = new DecimalPlus(4).times(arctan(new DecimalPlus(1).div(5)))
        .minus(arctan(new DecimalPlus(1).div(239)));

    // the final pi has the requested number of decimals
    return new Decimal(4).times(pi4th);
  }

  var calculatedPi = pi();
```

Both work fine. Machin's formula is in the order of 3 times faster than Bailey-Borwein-Plouffe. To calculate pi with 100 digits takes ~10ms, pi with 1000 digits takes ~180ms.

**Comment by kauegimenes** [comment]
@MikeMcl Its possible to use Chudnovsky or Bailey-Borwein-Plouffe to create a function that returns n digits from a given position in pi?

chudnovsky(digits, position)
chudnovsky(3, 0) returns `314`
chudnovsky(3, 10) returns `589`

**Comment by MikeMcl** [comment]
@kauegimenes 

Yes, I think you can use the [BBP formula](https://stackoverflow.com/questions/5905822/function-to-find-the-nth-digit-of-pi). If you can come up with an implementation that uses decimal.js, please post it.

**Comment by calidion** [comment]
what 's going on now? is bbp formula implemented?

**Comment by kauegimenes** [comment]
@calidion only got Chudnovsky and Bailey-Borwein-Plouffe working

**Comment by calidion** [comment]
maybe this c implement
https://bellard.org/pi/pi.c

worth referencing.

I would like to look into this when time permits.

**Comment by kauegimenes** [comment]
@calidion im publishing an npm package with my implementation of BBP

**Comment by kauegimenes** [comment]
@calidion it still need some work, but feel free to fork / contribute i will post the link for the repo in a few minutes.

**Comment by kauegimenes** [comment]
@calidion please check https://github.com/kauegimenes/bbp-formula
Its already published to npm feel free to create a PR if you find any problems.

**Comment by calidion** [comment]
@kauegimenes  

Greate job!

Can this version generate infinite precision if the precision is not specified?
