### ISSUE TITLE
Hex back to Decimal wrong?

### ISSUE THREAD

**Issue by benzon** [MikeMcl/decimal.js#90]
Hi,

Did a small test here, convertet a value to hex, and then convertet it back using toNumber but the result is off by 3 so it ends up giving a wrong result not sure why.

0x110000100007589 should give 76561197960295817 but gives 76561197960295820

**Comment by MikeMcl** [comment]
```js
new Decimal('0x110000100007589').toString()    // "76561197960295817"
new Decimal('0x110000100007589').toNumber()    // 76561197960295820
76561197960295817 === 76561197960295820        // true
```

That's a 17 digit number. What makes you think JavaScript numbers are that precise?
