### ISSUE TITLE
Converting number strings with '+' sign

### ISSUE THREAD

**Issue by denys-kostenko** [MikeMcl/decimal.js#93]
Hello!

I'm trying to create `new Decimal('+1')` and got an error, it's little confusing because `new Decimal('-1')` works well.

**Comment by MikeMcl** [comment]
Hello.
As this has been raised before in #32 and #60, I will consider readding support for a leading `+`.
In the meantime, try `new Decimal('1')`.

**Comment by denys-kostenko** [comment]
Thanks, one more argument for supporting this thing that native `Number` works well with leading plus.

FYI, @kcudnik, @aviaryan.

**Comment by adamreisnz** [comment]
Seems related, but it also fails on negative numbers, e.g.;

```
Error: [DecimalError] Invalid argument: -10
```

Why is that invalid input? Isn't the whole point of this library to normalize numbers?

**Comment by MikeMcl** [comment]
Added support for this in *v10.2.0*.
