### ISSUE TITLE
Naming of modules

### ISSUE THREAD

**Issue by adamreisnz** [MikeMcl/decimal.js#94]
Not a major issue, but I can't be the only one who finds the naming of these modules really confusing. It took me 3 tries to figure out which one I needed.

Bignumber.js is essentially like decimal.js, but it allows you to specify precision in decimals. Shouldn't bignumber.js then be called decimal.js and vice versa...? 😕

**Comment by MikeMcl** [comment]
>> Bignumber.js is essentially like decimal.js, but it allows you to specify precision in decimals

In decimal *places*, yes, but "in decimals" to me implies 'in numbers with fraction digits" or "in base 10 numbers" neither of which makes much sense.

*decimal.js* was originally a new version of *bignumber.js* which I decided to release as a separate library.

The names of the modules are not going to change at this point, and I am happy with them.
