### ISSUE TITLE
Add `subtract` as an alias for `sub`

### ISSUE THREAD

**Issue by adamreisnz** [MikeMcl/decimal.js#95]
```
TypeError: income.subtract is not a function
```

Some developers like to be verbose and don't like shorthand methods, as it can make the code poorly legible.

For example `sub` and mean different things, whereas `subtract` is unambiguous.

Currently, it doesn't make much sense having `minus` and a shorthand of that, `sub`. You'd expect this to be `subtract` and `sub`.

I propose the addition of a `subtract` alias for `sub`, not only for the above reason, but also to be consistent with other decimal modules out there.

**Comment by MikeMcl** [comment]
I don't like `sub` either. It was provided to meet another user's request and will probably be removed when I refresh this library in the near future. I don't want `subtract` though, it's `minus` here, and I'm not interested in being consistent with 'other decimal modules out there'.
